import { useState, useEffect } from 'react'
import { Link, Route, Switch } from 'wouter'
import { ArrowRight, BadgeDollarSign, House, Menu, X, Mail, Sparkles, LayoutDashboard, Box, Factory as FactoryIcon, FileCode } from 'lucide-react'
import avatar from './assets/mimi-avatar.png'
import creativeAdsLogo from './assets/mimis-creative-ads-logo.png'
import laTambora from './assets/la-tambora-sample.jpg'
const SUPA_URL = (import.meta as any).env?.VITE_SUPABASE_URL
const SUPA_KEY = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY
function Header(){const[open,setOpen]=useState(false);return(<header className="header"><div className="container header-inner"><Link href="/" className="logo">Mimi's Cozy Corner • Live DB</Link><nav className={open?"nav open":"nav"}><Link href="/"><House size={16}/> Home</Link><Link href="/dashboard"><LayoutDashboard size={16}/> Dash</Link><Link href="/blueprints"><FileCode size={16}/> Blueprints</Link><Link href="/products"><Box size={16}/> Products</Link><Link href="/product-factory"><FactoryIcon size={16}/> Factory</Link><Link href="/creative-ads"><BadgeDollarSign size={16}/> Ads $25</Link><Link href="/contact"><Mail size={16}/> Contact</Link></nav><button className="menu-btn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>)}
function Footer(){return<footer className="footer"><div className="container"><p>© 2026 Mimi's Cozy Corner - Live DB gjcmflhymliizvgtifjv ✅</p></div></footer>}
function useProducts(){const[products,setProducts]=useState<any[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{async function load(){if(!SUPA_URL||!SUPA_KEY){setProducts([{name:"Add Supabase URL in Cloudflare!"}]);setLoading(false);return}try{const r=await fetch(`${SUPA_URL}/rest/v1/products?select=*&limit=20`,{headers:{apikey:SUPA_KEY,Authorization:`Bearer ${SUPA_KEY}`}});const d=await r.json();setProducts(Array.isArray(d)&&d.length?d:[{name:"No products yet - Create in Factory!"}])}catch{setProducts([{name:"Offline"}])}setLoading(false)}load()},[]);return{products,loading}}
function Home(){const{products}=useProducts();return<><Header/><main><section className="hero"><div className="container hero-grid"><div><div className="eyebrow">{products.length} PRODUCTS LIVE FROM SUPABASE</div><h1>Atlas OS Live!</h1><p>Blueprints 404 fixed + Real DB</p><div className="cta-row" style={{display:'flex', gap:12, marginTop:20}}><Link className="button primary" href="/products">View {products.length} Products <ArrowRight size={18}/></Link></div></div><div className="avatar-card"><img src={avatar} alt="Mimi"/><div className="avatar-chip"><Sparkles size={15}/> Live</div></div></div></section></main><Footer/></>}
function Dashboard(){return<><Header/><main><section className="page-hero" style={{background:'#0a0a0a', color:'white'}}><div className="container"><h1>Dashboard - Live</h1></div></section></main><Footer/></>}
function Blueprints(){return<><Header/><main><section className="page-hero"><div className="container"><h1>Blueprints - 404 FIXED! ✅</h1><p>Was 2 empty folders - now working!</p></div></section></main><Footer/></>}
function Products(){const{products,loading}=useProducts();return<><Header/><main><section className="page-hero" style={{background:'#F0F7FF'}}><div className="container"><h1>Products - {loading?"Loading...":`${products.length} LIVE`}</h1><div style={{display:'grid', gap:12, marginTop:20}}>{products.map((p:any,i:number)=><div key={i} style={{background:'white', padding:16, borderRadius:12}}><strong>{p.name||p.title}</strong></div>)}</div></div></section></main><Footer/></>}
function ProductFactory(){const[name,setName]=useState("");const[msg,setMsg]=useState("");async function create(){if(!name)return setMsg("Enter name");if(!SUPA_URL)return setMsg("Update URL in Cloudflare!");setMsg("Creating...");const r=await fetch(`${SUPA_URL}/rest/v1/products`,{method:'POST',headers:{apikey:SUPA_KEY,Authorization:`Bearer ${SUPA_KEY}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({name,title:name,status:'Draft',price:'$25'})});setMsg(r.ok?"✅ Created! Check /products":`Error ${r.status}`);setName("")}return<><Header/><main><section className="page-hero" style={{background:'#FFF0F5'}}><div className="container" style={{maxWidth:600}}><h1>Factory</h1><div style={{background:'white', padding:20, borderRadius:12, marginTop:20}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Product name" style={{width:'100%', padding:12, borderRadius:8, border:'1px solid #ddd'}}/><button onClick={create} className="button primary" style={{width:'100%', marginTop:12}}>Create</button><p>{msg}</p></div></div></section></main><Footer/></>}
function CreativeAds(){return<><Header/><main><section className="page-hero"><div className="container" style={{maxWidth:700, textAlign:'center'}}><img src={creativeAdsLogo} alt="logo" style={{maxWidth:200, margin:'0 auto 20px'}}/><h1>Ads $25</h1><img src={laTambora} alt="ad" style={{width:'100%', borderRadius:16, margin:'20px 0'}}/></div></section></main><Footer/></>}
function Contact(){return<><Header/><main><section className="page-hero"><div className="container" style={{textAlign:'center'}}><h1>Contact</h1><p>@mimis_corner_co</p></div></section></main><Footer/></>}
export default function App(){return(<Switch><Route path="/"><Home/></Route><Route path="/dashboard"><Dashboard/></Route><Route path="/blueprints"><Blueprints/></Route><Route path="/products"><Products/></Route><Route path="/product-factory"><ProductFactory/></Route><Route path="/creative-ads"><CreativeAds/></Route><Route path="/contact"><Contact/></Route><Route><Home/></Route></Switch>)}
