import React, { useState, useMemo } from "react"
type Product = { id:number; name:string; price:number; collection:string; image:string }
const COLLECTIONS = ["All","Western","Trucker Hats","Bags","Fall","Graphic Tees","Hoodies","Shirts","Sweatshirts","Outerwear","Jewelry","Footwear","Bottoms","Accessories","Sale","New"]
const PRODUCTS: Product[] = [
 { id: 1, name: '0 Days Since My Last Dad Joke ', price: 18, collection: 'Graphic Tees', image: `/images/0%20Days%20since%20My%20Last%20Dad%20Joke%20.png` },
 { id: 2, name: '3F124Ede 6B08 46F2 89F6 8Bb1F8767E94', price: 19, collection: 'Graphic Tees', image: `/images/3f124ede-6b08-46f2-89f6-8bb1f8767e94.png` },
 { id: 3, name: 'Angels &Outlaws', price: 20, collection: 'Graphic Tees', image: `/images/ANGELS%20%26OUTLAWS.webp` },
 { id: 4, name: 'Ancient Flame (1000 X 1000 Px)', price: 21, collection: 'Graphic Tees', image: `/images/Ancient%20Flame%20%281000%20x%201000%20px%29.png` },
 { id: 5, name: 'Ancient Flame', price: 22, collection: 'Graphic Tees', image: `/images/Ancient%20Flame.PNG` },
 { id: 6, name: 'Bear Of Backyard Avoidance', price: 23, collection: 'Graphic Tees', image: `/images/BEAR%20OF%20BACKYARD%20AVOIDANCE.png` },
 { id: 7, name: 'Behind Every Great Kid', price: 24, collection: 'Graphic Tees', image: `/images/BEHIND%20EVERY%20GREAT%20KID.png` },
 { id: 8, name: 'Believe In Yourself (Bright)', price: 25, collection: 'Graphic Tees', image: `/images/BELIEVE%20in%20YOURSELF%20%28BRIGHT%29.png` },
 { id: 9, name: 'Believe In Yourself (Dreamy)', price: 26, collection: 'Graphic Tees', image: `/images/BELIEVE%20in%20YOURSELF%20%28DREAMY%29.png` },
 { id: 10, name: 'Believe In Yourself (Night)', price: 27, collection: 'Graphic Tees', image: `/images/BELIEVE%20in%20YOURSELF%20%28NIGHT%29.png` },
 { id: 11, name: 'Bookish', price: 28, collection: 'Graphic Tees', image: `/images/BOOKISH.png` },
 { id: 12, name: 'Burnt Out Crispy Unicorn', price: 29, collection: 'Graphic Tees', image: `/images/BURNT%20OUT%20CRISPY%20UNICORN.png` },
 { id: 13, name: 'Baby Huey', price: 30, collection: 'Graphic Tees', image: `/images/Baby%20Huey.png` },
 { id: 14, name: 'Balance.Png', price: 31, collection: 'Graphic Tees', image: `/images/Balance.PNG.png` },
 { id: 15, name: 'Best Dad By Par', price: 32, collection: 'Graphic Tees', image: `/images/Best%20Dad%20By%20Par.png` },
 { id: 16, name: 'Blade And Bloom', price: 33, collection: 'Graphic Tees', image: `/images/Blade%20and%20Bloom.png` },
 { id: 17, name: 'Blessed & Stressed (1)', price: 34, collection: 'Graphic Tees', image: `/images/Blessed%20%26%20Stressed%20%281%29.png` },
 { id: 18, name: 'Blessed & Stressed Mom Chaos (Black) (1000 X 1000 Px)', price: 35, collection: 'Graphic Tees', image: `/images/Blessed%20%26%20Stressed%20Mom%20Chaos%20%28Black%29%20%281000%20x%201000%20px%29.png` },
 { id: 19, name: 'Blessed & Stressed Mom Chaos(White Clear) (1000 X 1000 Px)', price: 36, collection: 'Graphic Tees', image: `/images/Blessed%20%26%20Stressed%20Mom%20Chaos%28white-clear%29%20%281000%20x%201000%20px%29.png` },
 { id: 20, name: 'Blessed, Stressed, And Caffeinated Chaos', price: 37, collection: 'Graphic Tees', image: `/images/Blessed%2C%20stressed%2C%20and%20caffeinated%20chaos.png` },
 { id: 21, name: 'Bloom Beast', price: 38, collection: 'Graphic Tees', image: `/images/Bloom%20Beast.png` },
 { id: 22, name: 'Bright Motion', price: 39, collection: 'Graphic Tees', image: `/images/Bright%20Motion.png` },
 { id: 23, name: 'Bright Star', price: 40, collection: 'Graphic Tees', image: `/images/Bright%20Star.PNG` },
 { id: 24, name: 'Brightscale Gecko', price: 41, collection: 'Graphic Tees', image: `/images/Brightscale%20Gecko.png` },
 { id: 25, name: 'Buffalo Of Budgeting Breakdown', price: 42, collection: 'Graphic Tees', image: `/images/Buffalo%20of%20Budgeting%20Breakdown.png` },
 { id: 26, name: 'Burst Of Color', price: 43, collection: 'Graphic Tees', image: `/images/Burst%20of%20Color.PNG` },
 { id: 27, name: 'Butterflies', price: 44, collection: 'Graphic Tees', image: `/images/Butterflies.JPG` },
 { id: 28, name: 'Calm Mind Club', price: 45, collection: 'Graphic Tees', image: `/images/CALM%20MIND%20CLUB.png` },
 { id: 29, name: 'Chaos & Crown', price: 46, collection: 'Graphic Tees', image: `/images/CHAOS%20%26%20CROWN.png` },
 { id: 30, name: 'Chill Out (Colorful) ', price: 47, collection: 'Graphic Tees', image: `/images/CHILL%20OUT%20%28COLORFUL%29%20.png` },
 { id: 31, name: 'Choose Calm (Plain)', price: 48, collection: 'Graphic Tees', image: `/images/CHOOSE%20CALM%20%28PLAIN%29.png` },
 { id: 32, name: 'Choose Calm (Zen)', price: 49, collection: 'Graphic Tees', image: `/images/CHOOSE%20CALM%20%28ZEN%29.png` },
 { id: 33, name: 'Colorful Abstract', price: 50, collection: 'Graphic Tees', image: `/images/COLORFUL%20ABSTRACT.png` },
 { id: 34, name: 'Colorful Abstract', price: 51, collection: 'Graphic Tees', image: `/images/COLORFUL%20ABSTRACT.webp` },
 { id: 35, name: 'Cozy Reader Club (Cozy)', price: 52, collection: 'Graphic Tees', image: `/images/COZY%20READER%20CLUB%20%28COZY%29.png` },
 { id: 36, name: 'Cozy Reader Club (Plain)', price: 53, collection: 'Graphic Tees', image: `/images/COZY%20READER%20CLUB%20%28PLAIN%29.png` },
 { id: 37, name: 'Cozy Vibes', price: 54, collection: 'Graphic Tees', image: `/images/COZY%20VIBES.png` },
 { id: 38, name: 'Cpromoted To Mom, Still Figuring It Out', price: 55, collection: 'Graphic Tees', image: `/images/CPromoted%20to%20mom%2C%20still%20figuring%20it%20out.png` },
 { id: 39, name: 'Caffeine Powered Survivor(4500 X 5400 Px)', price: 56, collection: 'Graphic Tees', image: `/images/Caffeine-Powered%20Survivor%284500%20x%205400%20px%29.webp` },
 { id: 40, name: 'Caffeine Powered Survivor', price: 57, collection: 'Graphic Tees', image: `/images/Caffeine-Powered%20Survivor.png` },
 { id: 41, name: 'Calm Mind Club (Dreamy)', price: 58, collection: 'Graphic Tees', image: `/images/Calm%20Mind%20Club%20%28dreamy%29.png` },
 { id: 42, name: 'Calm Mind Club (Zen)', price: 59, collection: 'Graphic Tees', image: `/images/Calm%20Mind%20Club%20%28zen%29.png` },
 { id: 43, name: 'Casting Spells Not Opinions', price: 18, collection: 'Graphic Tees', image: `/images/Casting%20Spells%20Not%20Opinions.png` },
 { id: 44, name: 'Castle Of The Day', price: 19, collection: 'Graphic Tees', image: `/images/Castle%20of%20the%20day.png` },
 { id: 45, name: 'Castle Of The Night', price: 20, collection: 'Graphic Tees', image: `/images/Castle%20of%20the%20night.jpg` },
 { id: 46, name: 'Castle', price: 21, collection: 'Graphic Tees', image: `/images/Castle.jpg` },
 { id: 47, name: 'Cat In Chaos Overload', price: 22, collection: 'Graphic Tees', image: `/images/Cat%20in%20chaos%20overload.png` },
 { id: 48, name: 'Celestial Gaze', price: 23, collection: 'Graphic Tees', image: `/images/Celestial%20Gaze.png` },
 { id: 49, name: 'Chiseling His Way ', price: 24, collection: 'Graphic Tees', image: `/images/Chiseling%20his%20way%20.png` },
 { id: 50, name: 'Choose Calm (Blue)', price: 25, collection: 'Graphic Tees', image: `/images/Choose%20Calm%20%28Blue%29.webp` },
 { id: 51, name: 'Choose Calm (Cozy)', price: 26, collection: 'Graphic Tees', image: `/images/Choose%20Calm%20%28cozy%29.webp` },
 { id: 52, name: 'Choose Calm (Green)', price: 27, collection: 'Graphic Tees', image: `/images/Choose%20Calm%20%28green%29.webp` },
 { id: 53, name: 'Chris 2024', price: 28, collection: 'Graphic Tees', image: `/images/Chris%202024.PNG` },
 { id: 54, name: 'Cloudy Train', price: 29, collection: 'Graphic Tees', image: `/images/Cloudy%20Train.png` },
 { id: 55, name: 'Color Burst (1000 X 1000 Px)', price: 30, collection: 'Graphic Tees', image: `/images/Color%20Burst%20%281000%20x%201000%20px%29.png` },
 { id: 56, name: 'Colorful Energy', price: 31, collection: 'Graphic Tees', image: `/images/Colorful%20Energy.png` },
 { id: 57, name: 'Colorful Windwhirl (1000 X 1000 Px)', price: 32, collection: 'Graphic Tees', image: `/images/Colorful%20Windwhirl%20%281000%20x%201000%20px%29.png` },
 { id: 58, name: 'Colorful Windwhirl', price: 33, collection: 'Graphic Tees', image: `/images/Colorful%20Windwhirl.png` },
 { id: 59, name: 'Coyote Of Car‑Ride Commentary', price: 34, collection: 'Graphic Tees', image: `/images/Coyote%20of%20Car%E2%80%91Ride%20Commentary.png` },
 { id: 60, name: 'Cozy Homebody Coffee', price: 35, collection: 'Graphic Tees', image: `/images/Cozy%20homebody%20coffee.png` },
 { id: 61, name: 'Crimson Spiral', price: 36, collection: 'Graphic Tees', image: `/images/Crimson%20Spiral.png` },
 { id: 62, name: 'Crown And Carnage.Png', price: 37, collection: 'Graphic Tees', image: `/images/Crown%20and%20Carnage.png.png` },
 { id: 63, name: 'Crying A River', price: 38, collection: 'Graphic Tees', image: `/images/Crying%20a%20river.png` },
 { id: 64, name: 'Cultivating Self Compassion', price: 39, collection: 'Graphic Tees', image: `/images/Cultivating%20Self-Compassion.png` },
 { id: 65, name: 'Dads Dance Moves', price: 40, collection: 'Graphic Tees', image: `/images/DADS%20DANCE%20MOVES.png` },
 { id: 66, name: 'Dog Of Dad Jokes', price: 41, collection: 'Graphic Tees', image: `/images/DOG%20OF%20DAD%20JOKES.png` },
 { id: 67, name: 'Done Dragon', price: 42, collection: 'Graphic Tees', image: `/images/DONE%20DRAGON.png` },
 { id: 68, name: 'Done Dragon', price: 43, collection: 'Graphic Tees', image: `/images/DONE%20DRAGON.webp` },
 { id: 69, name: 'Dad Because Grandpa Wasn’T Cool Enough', price: 44, collection: 'Graphic Tees', image: `/images/Dad%20Because%20Grandpa%20Wasn%E2%80%99t%20Cool%20Enough.png` },
 { id: 70, name: 'Dad Bod Built By Bbq And Bad Decisions', price: 45, collection: 'Graphic Tees', image: `/images/Dad%20Bod%20Built%20by%20BBQ%20and%20Bad%20Decisions.png` },
 { id: 71, name: 'Dad Eats My Fries', price: 46, collection: 'Graphic Tees', image: `/images/Dad%20Eats%20My%20Fries.png` },
 { id: 72, name: 'Dad Fueling The Family With Dad Jokes & Coffee', price: 47, collection: 'Graphic Tees', image: `/images/Dad%20Fueling%20the%20Family%20With%20Dad%20Jokes%20%26%20Coffee.png` },
 { id: 73, name: 'Dad Jokes Are How Eye Roll', price: 48, collection: 'Graphic Tees', image: `/images/Dad%20Jokes%20Are%20How%20Eye%20Roll.png` },
 { id: 74, name: 'Dad Life Powered By Coffee And Patience', price: 49, collection: 'Graphic Tees', image: `/images/Dad%20Life%20Powered%20by%20Coffee%20and%20Patience.png` },
 { id: 75, name: 'Dad Master Of The Remote Control', price: 50, collection: 'Graphic Tees', image: `/images/Dad%20Master%20of%20the%20Remote%20Control.png` },
 { id: 76, name: 'Dad Professional Thermostat Protector', price: 51, collection: 'Graphic Tees', image: `/images/Dad%20Professional%20Thermostat%20Protector.png` },
 { id: 77, name: 'Dad Sacrificing Sleep Since Forever', price: 52, collection: 'Graphic Tees', image: `/images/Dad%20Sacrificing%20Sleep%20Since%20Forever.png` },
 { id: 78, name: 'Dad Tax Taking A Piece Of Your Snacks Since Day One', price: 53, collection: 'Graphic Tees', image: `/images/Dad%20Tax%20Taking%20a%20Piece%20of%20Your%20Snacks%20Since%20Day%20One.png` },
 { id: 79, name: 'Dad The Human Instructions Nobody Reads', price: 54, collection: 'Graphic Tees', image: `/images/Dad%20The%20Human%20Instructions%20Nobody%20Reads.png` },
 { id: 80, name: 'Dad’S Bbq Rule #1 If I’M Cooking, Stay Out Of My Kitchen', price: 55, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20BBQ%20Rule%20%231%20If%20I%E2%80%99m%20Cooking%2C%20Stay%20Out%20of%20My%20Kitchen.png` },
 { id: 81, name: 'Dad’S Chair Touch It And You’Re Grounded', price: 56, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Chair%20Touch%20It%20and%20You%E2%80%99re%20Grounded.png` },
 { id: 82, name: 'Dad’S Cooking Timer “I’Ll Know When It’S Done”', price: 57, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Cooking%20Timer%20%E2%80%9CI%E2%80%99ll%20Know%20When%20It%E2%80%99s%20Done%E2%80%9D.png` },
 { id: 83, name: 'Dad’S Driving Rules Silence Means I Missed The Turn', price: 58, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Driving%20Rules%20Silence%20Means%20I%20Missed%20the%20Turn.png` },
 { id: 84, name: 'Dad’S Favorite Child Depends On Who Has Snacks', price: 59, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Favorite%20Child%20Depends%20on%20Who%20Has%20Snacks.png` },
 { id: 85, name: 'Dad’S Favorite Exercise Walking To The Fridge', price: 18, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Favorite%20Exercise%20Walking%20to%20the%20Fridge.png` },
 { id: 86, name: 'Dad’S Garage My Tools, My Rules', price: 19, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Garage%20My%20Tools%2C%20My%20Rules.png` },
 { id: 87, name: 'Dad’S Garage Where Projects Go To Never Be Finished', price: 20, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Garage%20Where%20Projects%20Go%20to%20Never%20Be%20Finished.png` },
 { id: 88, name: 'Dad’S Gas Station Stop Somehow Costs $47 Every Time', price: 21, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Gas%20Station%20Stop%20Somehow%20Costs%20%2447%20Every%20Time.png` },
 { id: 89, name: 'Dad’S Grill Schedule Burnt Outside, Raw Inside, Full Confidence', price: 22, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Grill%20Schedule%20Burnt%20Outside%2C%20Raw%20Inside%2C%20Full%20Confidence.png` },
 { id: 90, name: 'Dad’S Grocery Store Mission Go In For One Thing, Leave With 37 Snacks', price: 23, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Grocery%20Store%20Mission%20Go%20In%20for%20One%20Thing%2C%20Leave%20With%2037%20Snacks.png` },
 { id: 91, name: 'Dad’S Hearing Works Selectively', price: 24, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Hearing%20Works%20Selectively.png` },
 { id: 92, name: 'Dad’S Lawn Rules Stripes Matter More Than Feelings', price: 25, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Lawn%20Rules%20Stripes%20Matter%20More%20Than%20Feelings.png` },
 { id: 93, name: 'Dad’S Nap The Most Protected Event In The House', price: 26, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Nap%20The%20Most%20Protected%20Event%20in%20the%20House.png` },
 { id: 94, name: 'Dad’S Official Language Grunts, Sighs & Dad Jokes', price: 27, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Official%20Language%20Grunts%2C%20Sighs%20%26%20Dad%20Jokes.png` },
 { id: 95, name: 'Dad’S Remote Control Rights Nobody Else Touches It', price: 28, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Remote%20Control%20Rights%20Nobody%20Else%20Touches%20It.png` },
 { id: 96, name: 'Dad’S Snack Stash Hidden Better Than Government Secrets', price: 29, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Snack%20Stash%20Hidden%20Better%20Than%20Government%20Secrets.png` },
 { id: 97, name: 'Dad’S Texting Style One Word Replies & Zero Punctuation', price: 30, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Texting%20Style%20One%20Word%20Replies%20%26%20Zero%20Punctuation.png` },
 { id: 98, name: 'Dad’S Toolbox Full Of Tools He’Ll Never Let You Borrow', price: 31, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Toolbox%20Full%20of%20Tools%20He%E2%80%99ll%20Never%20Let%20You%20Borrow.png` },
 { id: 99, name: 'Dad’S Universal Fix “Put Some Duct Tape On It”', price: 32, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Universal%20Fix%20%E2%80%9CPut%20Some%20Duct%20Tape%20On%20It%E2%80%9D.png` },
 { id: 100, name: 'Dad’S Vacation Packing List 14 Cords, 2 Coolers & Zero Shirts', price: 33, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Vacation%20Packing%20List%2014%20Cords%2C%202%20Coolers%20%26%20Zero%20Shirts.png` },
 { id: 101, name: 'Dad’S Wallet Opens Faster At The Hardware Store', price: 34, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Wallet%20Opens%20Faster%20at%20the%20Hardware%20Store.png` },
 { id: 102, name: 'Dad’S Weather Forecast “Yep… It’S Hot Outside”', price: 35, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Weather%20Forecast%20%E2%80%9CYep%E2%80%A6%20It%E2%80%99s%20Hot%20Outside%E2%80%9D.png` },
 { id: 103, name: 'Divine Light Within', price: 36, collection: 'Graphic Tees', image: `/images/Divine%20Light%20Within.png` },
 { id: 104, name: 'Divine And Damned', price: 37, collection: 'Graphic Tees', image: `/images/Divine%20and%20Damned.png` },
 { id: 105, name: 'Dragon Of Domestic Doom', price: 38, collection: 'Graphic Tees', image: `/images/Dragon%20of%20Domestic%20Doom.png` },
 { id: 106, name: 'Dragon', price: 39, collection: 'Graphic Tees', image: `/images/Dragon.png` },
 { id: 107, name: 'Dream Beyond The Clouds', price: 40, collection: 'Graphic Tees', image: `/images/Dream%20beyond%20the%20clouds.png` },
 { id: 108, name: 'Drowning In Thought', price: 41, collection: 'Graphic Tees', image: `/images/Drowning%20in%20thought.png` },
 { id: 109, name: 'El General', price: 42, collection: 'Graphic Tees', image: `/images/EL%20GENERAL.png` },
 { id: 110, name: 'Earth, Fire, Wind, Water', price: 43, collection: 'Graphic Tees', image: `/images/Earth%2C%20Fire%2C%20Wind%2C%20Water.PNG` },
 { id: 111, name: 'Echo Of Color ', price: 44, collection: 'Graphic Tees', image: `/images/Echo%20of%20Color%20.png` },
 { id: 112, name: 'Echoes Of The Ascendant Stone', price: 45, collection: 'Graphic Tees', image: `/images/Echoes%20of%20the%20Ascendant%20Stone.png` },
 { id: 113, name: 'Embrace The Unexpected', price: 46, collection: 'Graphic Tees', image: `/images/Embrace%20the%20unexpected.png` },
 { id: 114, name: 'Energy (1000 X 1000 Px)', price: 47, collection: 'Graphic Tees', image: `/images/Energy%20%281000%20x%201000%20px%29.png` },
 { id: 115, name: 'Energy', price: 48, collection: 'Graphic Tees', image: `/images/Energy.png` },
 { id: 116, name: 'Explorer Fox – Adventure Awaits!', price: 49, collection: 'Graphic Tees', image: `/images/Explorer%20Fox%20%E2%80%93%20Adventure%20Awaits%21.png` },
 { id: 117, name: 'Eye Of The Spirits', price: 50, collection: 'Graphic Tees', image: `/images/Eye%20of%20the%20Spirits.PNG` },
 { id: 118, name: 'Fire Of Myth (1)', price: 51, collection: 'Graphic Tees', image: `/images/Fire%20of%20Myth%20%281%29.png` },
 { id: 119, name: 'First My Mother, Forever My Friend (2)', price: 52, collection: 'Graphic Tees', image: `/images/First%20my%20mother%2C%20forever%20my%20friend%20%282%29.png` },
 { id: 120, name: 'First My Mother, Forever My Friend 2', price: 53, collection: 'Graphic Tees', image: `/images/First%20my%20mother%2C%20forever%20my%20friend%202.png` },
 { id: 121, name: 'First My Mother, Forever My Friend', price: 54, collection: 'Graphic Tees', image: `/images/First%20my%20mother%2C%20forever%20my%20friend.png` },
 { id: 122, name: 'Forces Of Energy', price: 55, collection: 'Graphic Tees', image: `/images/Forces%20of%20Energy.png` },
 { id: 123, name: 'Forge Truth', price: 56, collection: 'Graphic Tees', image: `/images/Forge%20Truth.PNG` },
 { id: 124, name: 'Fuck Off!', price: 57, collection: 'Graphic Tees', image: `/images/Fuck%20Off%21.jpg` },
 { id: 125, name: 'Fuck Off!', price: 58, collection: 'Graphic Tees', image: `/images/Fuck%20Off%21.png` },
 { id: 126, name: 'Funny Mom Humor Moth', price: 59, collection: 'Graphic Tees', image: `/images/Funny%20Mom%20Humor%20Moth.png` },
 { id: 127, name: 'Funny Parent', price: 18, collection: 'Graphic Tees', image: `/images/Funny%20Parent.png` },
 { id: 128, name: 'Grim ', price: 19, collection: 'Graphic Tees', image: `/images/GRIM%20.png` },
 { id: 129, name: 'Garden Of Love (1)', price: 20, collection: 'Graphic Tees', image: `/images/Garden%20of%20Love%20%281%29.png` },
 { id: 130, name: 'Genie Of Gendered Expectations', price: 21, collection: 'Graphic Tees', image: `/images/Genie%20of%20Gendered%20Expectations.png` },
 { id: 131, name: 'Glowing Butterflies ', price: 22, collection: 'Graphic Tees', image: `/images/Glowing%20Butterflies%20.webp` },
 { id: 132, name: 'Glowing Woman.Png', price: 23, collection: 'Graphic Tees', image: `/images/Glowing%20Woman.PNG.png` },
 { id: 133, name: 'Goat Of Grocery Rage   1', price: 24, collection: 'Graphic Tees', image: `/images/Goat%20of%20Grocery%20Rage%20-%201.png` },
 { id: 134, name: 'Goat Of Grunt‑Based Communication   1', price: 25, collection: 'Graphic Tees', image: `/images/Goat%20of%20Grunt%E2%80%91Based%20Communication%20-%201.png` },
 { id: 135, name: 'God Sent Kids And Blessings', price: 26, collection: 'Graphic Tees', image: `/images/God-sent%20kids%20and%20blessings.png` },
 { id: 136, name: 'Goddess Of Water (1000 X 1000 Px)', price: 27, collection: 'Graphic Tees', image: `/images/Goddess%20of%20Water%20%281000%20x%201000%20px%29.png` },
 { id: 137, name: 'Goddess Of Water ', price: 28, collection: 'Graphic Tees', image: `/images/Goddess%20of%20Water%20.png` },
 { id: 138, name: 'Healing In Progress (Bright)', price: 29, collection: 'Graphic Tees', image: `/images/HEALING%20in%20PROGRESS%20%28BRIGHT%29.png` },
 { id: 139, name: 'Healing In Progress (Calm) ', price: 30, collection: 'Graphic Tees', image: `/images/HEALING%20in%20PROGRESS%20%28CALM%29%20.png` },
 { id: 140, name: 'Healing In Progress (Glow) ', price: 31, collection: 'Graphic Tees', image: `/images/HEALING%20in%20PROGRESS%20%28GLOW%29%20.png` },
 { id: 141, name: 'Healing In Progress (Plain) ', price: 32, collection: 'Graphic Tees', image: `/images/HEALING%20in%20PROGRESS%20%28PLAIN%29%20.png` },
 { id: 142, name: 'Happy Dino Trio', price: 33, collection: 'Graphic Tees', image: `/images/Happy%20Dino%20Trio.png` },
 { id: 143, name: 'Happy Father’S Day To The Guy Who Always Knows A Shortcut', price: 34, collection: 'Graphic Tees', image: `/images/Happy%20Father%E2%80%99s%20Day%20to%20the%20Guy%20Who%20Always%20Knows%20a%20Shortcut.png` },
 { id: 144, name: 'Happy Father’S Day To The Guy Who Still Thinks He’S Funny', price: 35, collection: 'Graphic Tees', image: `/images/Happy%20Father%E2%80%99s%20Day%20to%20the%20Guy%20Who%20Still%20Thinks%20He%E2%80%99s%20Funny.png` },
 { id: 145, name: 'Happy Father’S Day To The King Of Dad Jokes', price: 36, collection: 'Graphic Tees', image: `/images/Happy%20Father%E2%80%99s%20Day%20to%20the%20King%20of%20Dad%20Jokes.png` },
 { id: 146, name: 'Happy Father’S Day To The Original Superhero', price: 37, collection: 'Graphic Tees', image: `/images/Happy%20Father%E2%80%99s%20Day%20to%20the%20Original%20Superhero.png` },
 { id: 147, name: 'Harmony (1000 X 1000 Px)', price: 38, collection: 'Graphic Tees', image: `/images/Harmony%20%281000%20x%201000%20px%29.png` },
 { id: 148, name: 'Harmony', price: 39, collection: 'Graphic Tees', image: `/images/Harmony.png` },
 { id: 149, name: 'Harry Potter', price: 40, collection: 'Graphic Tees', image: `/images/Harry%20Potter.png` },
 { id: 150, name: 'Heaven And Havoc ', price: 41, collection: 'Graphic Tees', image: `/images/Heaven%20and%20Havoc%20.png` },
 { id: 151, name: 'Hedgehog’S Guide To Social Anxiety', price: 42, collection: 'Graphic Tees', image: `/images/Hedgehog%E2%80%99s%20guide%20to%20social%20anxiety.png` },
 { id: 152, name: 'High Hound', price: 43, collection: 'Graphic Tees', image: `/images/High%20Hound.jpg` },
 { id: 153, name: 'High Hound', price: 44, collection: 'Graphic Tees', image: `/images/High%20Hound.png` },
 { id: 154, name: 'Highway Tower  (1000 X 1000 Px)', price: 45, collection: 'Graphic Tees', image: `/images/Highway%20Tower%20%20%281000%20x%201000%20px%29.png` },
 { id: 155, name: 'Highway Tower  ', price: 46, collection: 'Graphic Tees', image: `/images/Highway%20Tower%20%20.png` },
 { id: 156, name: 'Hippo Of Half‑Finished Projects', price: 47, collection: 'Graphic Tees', image: `/images/Hippo%20of%20Half%E2%80%91Finished%20Projects.png` },
 { id: 157, name: 'Home Is Where Mom Is Loved', price: 48, collection: 'Graphic Tees', image: `/images/Home%20is%20where%20Mom%20is%20loved.png` },
 { id: 158, name: 'Home Is Wherever Mom Is', price: 49, collection: 'Graphic Tees', image: `/images/Home%20is%20wherever%20mom%20is.png` },
 { id: 159, name: 'Hypno Fusion Petal', price: 50, collection: 'Graphic Tees', image: `/images/Hypno%20Fusion%20Petal.png` },
 { id: 160, name: 'I Am Confident', price: 51, collection: 'Graphic Tees', image: `/images/I%20AM%20CONFIDENT.png` },
 { id: 161, name: 'I Am Strong', price: 52, collection: 'Graphic Tees', image: `/images/I%20Am%20Strong.png` },
 { id: 162, name: 'I Can’T Fix Stupid, But I Can Fix Most Things', price: 53, collection: 'Graphic Tees', image: `/images/I%20Can%E2%80%99t%20Fix%20Stupid%2C%20But%20I%20Can%20Fix%20Most%20Things.png` },
 { id: 163, name: 'I Don’T Snore. I Dream I’M A Motorcycle.', price: 54, collection: 'Graphic Tees', image: `/images/I%20Don%E2%80%99t%20Snore.%20I%20Dream%20I%E2%80%99m%20a%20Motorcycle..png` },
 { id: 164, name: 'I Make Awesome Kids. You’Re Welcome.', price: 55, collection: 'Graphic Tees', image: `/images/I%20Make%20Awesome%20Kids.%20You%E2%80%99re%20Welcome..png` },
 { id: 165, name: 'I Am The Storm', price: 56, collection: 'Graphic Tees', image: `/images/I%20am%20The%20Storm.png` },
 { id: 166, name: 'I Am Connected To The Divine', price: 57, collection: 'Graphic Tees', image: `/images/I%20am%20connected%20to%20the%20divine.png` },
 { id: 167, name: 'I Embody The Power Of The Ancients', price: 58, collection: 'Graphic Tees', image: `/images/I%20embody%20the%20power%20of%20the%20ancients.png` },
 { id: 168, name: 'I Run On Coffee And Chaos', price: 59, collection: 'Graphic Tees', image: `/images/I%20run%20on%20coffee%20and%20chaos.png` },
 { id: 169, name: 'I Survied To Many Storms To Be Bothered By Raindrops', price: 18, collection: 'Graphic Tees', image: `/images/I%20survied%20to%20many%20storms%20to%20be%20bothered%20by%20raindrops.png` },
 { id: 170, name: 'I Will Not Give Up My Power!', price: 19, collection: 'Graphic Tees', image: `/images/I%20will%20not%20give%20up%20my%20Power%21.png` },
 { id: 171, name: 'Inner Self Pic', price: 20, collection: 'Graphic Tees', image: `/images/Inner%20self%20pic.png` },
 { id: 172, name: 'Insane Rat', price: 21, collection: 'Graphic Tees', image: `/images/Insane%20Rat.png` },
 { id: 173, name: 'I’M Not Arguing. I’M Just Explaining Why I’M Right.', price: 22, collection: 'Graphic Tees', image: `/images/I%E2%80%99m%20Not%20Arguing.%20I%E2%80%99m%20Just%20Explaining%20Why%20I%E2%80%99m%20Right..png` },
 { id: 174, name: 'Kindness Bear – Be Kind, Be Brave ', price: 23, collection: 'Graphic Tees', image: `/images/Kindness%20Bear%20%E2%80%93%20Be%20Kind%2C%20Be%20Brave%20.png` },
 { id: 175, name: 'Leaving In 5 Minutes… Not Really', price: 24, collection: 'Graphic Tees', image: `/images/Leaving%20in%205%20Minutes%E2%80%A6%20Not%20Really.png` },
 { id: 176, name: 'Light In The Sky', price: 25, collection: 'Graphic Tees', image: `/images/Light%20in%20the%20Sky.PNG` },
 { id: 177, name: 'Lightening Fights', price: 26, collection: 'Graphic Tees', image: `/images/Lightening%20Fights.PNG` },
 { id: 178, name: 'Lion Of Lost Tools', price: 27, collection: 'Graphic Tees', image: `/images/Lion%20of%20Lost%20Tools.png` },
 { id: 179, name: 'Live Free Image', price: 28, collection: 'Graphic Tees', image: `/images/Live%20Free%20Image.png` },
 { id: 180, name: 'Lizard Of Lawn Obsession', price: 29, collection: 'Graphic Tees', image: `/images/Lizard%20of%20lawn%20obsession.png` },
 { id: 181, name: 'Locked Dove', price: 30, collection: 'Graphic Tees', image: `/images/Locked%20Dove.png` },
 { id: 182, name: 'Lust And Loyalty', price: 31, collection: 'Graphic Tees', image: `/images/Lust%20and%20Loyalty.png` },
 { id: 183, name: 'My Dad Eats My Fries   1', price: 32, collection: 'Graphic Tees', image: `/images/MY%20DAD%20EATS%20MY%20FRIES%20-%201.webp` },
 { id: 184, name: 'My Dads Super Power', price: 33, collection: 'Graphic Tees', image: `/images/MY%20DADS%20SUPER%20POWER.png` },
 { id: 185, name: 'Make Something New', price: 34, collection: 'Graphic Tees', image: `/images/Make%20something%20new.png` },
 { id: 186, name: 'Mama Needs Wine (Lucid Yellow)', price: 35, collection: 'Graphic Tees', image: `/images/Mama%20Needs%20Wine%20%28Lucid-Yellow%29.png` },
 { id: 187, name: 'Mama Bear And Her Cubs', price: 36, collection: 'Graphic Tees', image: `/images/Mama%20bear%20and%20her%20cubs.png` },
 { id: 188, name: 'Mama Needs Wine And Survival', price: 37, collection: 'Graphic Tees', image: `/images/Mama%20needs%20wine%20and%20survival.png` },
 { id: 189, name: 'Mentally At Home', price: 38, collection: 'Graphic Tees', image: `/images/Mentally%20at%20Home.png` },
 { id: 190, name: 'Messy Mom Life Fueled By Faith', price: 39, collection: 'Graphic Tees', image: `/images/Messy%20mom%20life%20fueled%20by%20faith.png` },
 { id: 191, name: 'Messy Mom Life  Fueled By Faith', price: 40, collection: 'Graphic Tees', image: `/images/Messy%20mom%20life_%20fueled%20by%20faith.png` },
 { id: 192, name: 'Mideviel Image', price: 41, collection: 'Graphic Tees', image: `/images/Mideviel%20image.png` },
 { id: 193, name: 'Mindful Zen Bath', price: 42, collection: 'Graphic Tees', image: `/images/Mindful%20Zen%20Bath.png` },
 { id: 194, name: 'Mom The Original Sea', price: 43, collection: 'Graphic Tees', image: `/images/Mom%20The%20Original%20Sea.png` },
 { id: 195, name: 'Mom At 2 Percent', price: 44, collection: 'Graphic Tees', image: `/images/Mom%20at%202%20Percent.png` },
 { id: 196, name: 'Mom Boss Vibes In Full Force', price: 45, collection: 'Graphic Tees', image: `/images/Mom%20boss%20vibes%20in%20full%20force.png` },
 { id: 197, name: 'Mom Fuel And Toddler Chaos', price: 46, collection: 'Graphic Tees', image: `/images/Mom%20fuel%20and%20toddler%20chaos.png` },
 { id: 198, name: 'Mom Life In Full Swing', price: 47, collection: 'Graphic Tees', image: `/images/Mom%20life%20in%20full%20swing.png` },
 { id: 199, name: 'Mom Life  Fueled By Love And Coffee', price: 48, collection: 'Graphic Tees', image: `/images/Mom%20life_%20fueled%20by%20love%20and%20coffee.png` },
 { id: 200, name: 'Mom, The Ultimate Search Engine', price: 49, collection: 'Graphic Tees', image: `/images/Mom%2C%20the%20ultimate%20search%20engine.png` },
 { id: 201, name: 'Mom  The Ultimate Search Engine', price: 50, collection: 'Graphic Tees', image: `/images/Mom_%20the%20ultimate%20search%20engine.png` },
 { id: 202, name: 'Monkey Of Mental Load Mayhem', price: 51, collection: 'Graphic Tees', image: `/images/Monkey%20of%20Mental%20Load%20Mayhem.webp` },
 { id: 203, name: 'Moose Of Miscommunication', price: 52, collection: 'Graphic Tees', image: `/images/Moose%20of%20Miscommunication.png` },
 { id: 204, name: 'Motherhood Chaos  Fueled By Love And Coffee', price: 53, collection: 'Graphic Tees', image: `/images/Motherhood%20chaos_%20fueled%20by%20love%20and%20coffee.png` },
 { id: 205, name: 'Motherhoodthe Toughest Job, Powered By Love 100X100   1', price: 54, collection: 'Graphic Tees', image: `/images/Motherhoodthe%20Toughest%20Job%2C%20Powered%20by%20Love%20100X100%20-%201.png` },
 { id: 206, name: 'Mowing Grass Icon', price: 55, collection: 'Graphic Tees', image: `/images/Mowing%20Grass%20Icon.png` },
 { id: 207, name: 'My Give A Damn’S Busted ', price: 56, collection: 'Graphic Tees', image: `/images/My%20Give%20A%20Damn%E2%80%99s%20Busted%20.webp` },
 { id: 208, name: 'My Give A Damn’S Busted', price: 57, collection: 'Graphic Tees', image: `/images/My%20Give%20a%20Damn%E2%80%99S%20Busted.png` },
 { id: 209, name: 'Mystical', price: 58, collection: 'Graphic Tees', image: `/images/Mystical.png` },
 { id: 210, name: 'Mythical Moon Castle', price: 59, collection: 'Graphic Tees', image: `/images/Mythical%20moon%20Castle.png` },
 { id: 211, name: 'Octopus Of Overcommitment   1', price: 18, collection: 'Graphic Tees', image: `/images/Octopus%20of%20Overcommitment%20-%201.png` },
 { id: 212, name: 'Octopus Of Overcommitment 2   1', price: 19, collection: 'Graphic Tees', image: `/images/Octopus%20of%20Overcommitment%202%20-%201.webp` },
 { id: 213, name: 'Octopus Of Overcommitment 2', price: 20, collection: 'Graphic Tees', image: `/images/Octopus%20of%20Overcommitment%202.png` },
 { id: 214, name: 'Octopus Of Overcommitment 2', price: 21, collection: 'Graphic Tees', image: `/images/Octopus%20of%20Overcommitment%202.webp` },
 { id: 215, name: 'Octopus Of Overcommitment', price: 22, collection: 'Graphic Tees', image: `/images/Octopus%20of%20Overcommitment.webp` },
 { id: 216, name: 'Octopus Overwhelmed With Responsibilities', price: 23, collection: 'Graphic Tees', image: `/images/Octopus%20overwhelmed%20with%20responsibilities.png` },
 { id: 217, name: 'One More Store', price: 24, collection: 'Graphic Tees', image: `/images/One%20More%20Store.webp` },
 { id: 218, name: 'Otter Of Overexplaining', price: 25, collection: 'Graphic Tees', image: `/images/Otter%20of%20Overexplaining.png` },
 { id: 219, name: 'Over It Owl   1', price: 26, collection: 'Graphic Tees', image: `/images/Over%20It%20Owl%20-%201.png` },
 { id: 220, name: 'Owl Of Overthinking', price: 27, collection: 'Graphic Tees', image: `/images/Owl%20of%20Overthinking.png` },
 { id: 221, name: 'Owl Of Overthinking', price: 28, collection: 'Graphic Tees', image: `/images/Owl%20of%20Overthinking.webp` },
 { id: 222, name: 'Peace Over Everything (Hippie)', price: 29, collection: 'Graphic Tees', image: `/images/PEACE%20over%20EVERYTHING%20%28HIPPIE%29.png` },
 { id: 223, name: 'Peace Over Everything (Plain)', price: 30, collection: 'Graphic Tees', image: `/images/PEACE%20over%20EVERYTHING%20%28PLAIN%29.png` },
 { id: 224, name: 'Peace Over Everything (Wave)', price: 31, collection: 'Graphic Tees', image: `/images/PEACE%20over%20EVERYTHING%20%28Wave%29.png` },
 { id: 225, name: 'Protect Your Peace (Plain)', price: 32, collection: 'Graphic Tees', image: `/images/PROTECT%20YOUR%20PEACE%20%28PLAIN%29.png` },
 { id: 226, name: 'Protect Your Peace (Wave)', price: 33, collection: 'Graphic Tees', image: `/images/PROTECT%20YOUR%20PEACE%20%28WAVE%29.png` },
 { id: 227, name: 'Protect Your Peace (Zen) ', price: 34, collection: 'Graphic Tees', image: `/images/PROTECT%20YOUR%20PEACE%20%28ZEN%29%20.png` },
 { id: 228, name: 'Parenting Demon Mode', price: 35, collection: 'Graphic Tees', image: `/images/Parenting%20Demon%20Mode.png` },
 { id: 229, name: 'Pelican Of Over Passive Parenting(1)', price: 36, collection: 'Graphic Tees', image: `/images/Pelican%20of%20over%20passive%20parenting%281%29.png` },
 { id: 230, name: 'Petals Of Power, Blades Of Truth', price: 37, collection: 'Graphic Tees', image: `/images/Petals%20of%20Power%2C%20Blades%20of%20Truth.png` },
 { id: 231, name: 'Power Of Legends', price: 38, collection: 'Graphic Tees', image: `/images/Power%20of%20Legends.png` },
 { id: 232, name: 'Professional Snack Provider And Boo Boo Fixer', price: 39, collection: 'Graphic Tees', image: `/images/Professional%20snack%20provider%20and%20boo%20boo%20fixer.png` },
 { id: 233, name: 'Professional Snack Provider, Boo Boo Fixer 2', price: 40, collection: 'Graphic Tees', image: `/images/Professional%20snack%20provider%2C%20boo%20boo%20fixer%202.png` },
 { id: 234, name: 'Promoted To Mom, Still Figuring It Out', price: 41, collection: 'Graphic Tees', image: `/images/Promoted%20to%20mom%2C%20still%20figuring%20it%20out.png` },
 { id: 235, name: 'Protect Your Energy', price: 42, collection: 'Graphic Tees', image: `/images/Protect%20your%20energy.png` },
 { id: 236, name: 'Queen Mom Vibes And Royal Energy', price: 43, collection: 'Graphic Tees', image: `/images/Queen%20mom%20vibes%20and%20royal%20energy.png` },
 { id: 237, name: 'Read More Books (Colorful)', price: 44, collection: 'Graphic Tees', image: `/images/READ%20MORE%20BOOKS%20%28COLORFUL%29.png` },
 { id: 238, name: 'Read More Books (Purple)', price: 45, collection: 'Graphic Tees', image: `/images/READ%20MORE%20BOOKS%20%28PURPLE%29.png` },
 { id: 239, name: 'Raccoon In Perpetual Chaos', price: 46, collection: 'Graphic Tees', image: `/images/Raccoon%20in%20perpetual%20chaos.png` },
 { id: 240, name: 'Raccoon Of Remote Control Rage', price: 47, collection: 'Graphic Tees', image: `/images/Raccoon%20of%20Remote%20Control%20Rage.png` },
 { id: 241, name: 'Rainbow Unicorn – Shine Bright!', price: 48, collection: 'Graphic Tees', image: `/images/Rainbow%20Unicorn%20%E2%80%93%20Shine%20Bright%21.png` },
 { id: 242, name: 'Reading Bunny', price: 49, collection: 'Graphic Tees', image: `/images/Reading%20Bunny.png` },
 { id: 243, name: 'Realms Of Wonder', price: 50, collection: 'Graphic Tees', image: `/images/Realms%20of%20Wonder.png` },
 { id: 244, name: 'Reclaiming Your Emotional Intuition', price: 51, collection: 'Graphic Tees', image: `/images/Reclaiming%20Your%20Emotional%20Intuition.png` },
 { id: 245, name: 'Sinners & Saints    1', price: 52, collection: 'Graphic Tees', image: `/images/SINNERS%20%26%20SAINTS%20%20-%201.png` },
 { id: 246, name: 'Sinners And Saints', price: 53, collection: 'Graphic Tees', image: `/images/SINNERS%20AND%20SAINTS.png` },
 { id: 247, name: 'Stay Calm (Blue,Green)', price: 54, collection: 'Graphic Tees', image: `/images/STAY%20CALM%20%28BLUE%2CGREEN%29.png` },
 { id: 248, name: 'Stay Calm (Colorful) ', price: 55, collection: 'Graphic Tees', image: `/images/STAY%20CALM%20%28COLORFUL%29%20.png` },
 { id: 249, name: 'Stay Calm (Plain)', price: 56, collection: 'Graphic Tees', image: `/images/STAY%20CALM%20%28PLAIN%29.png` },
 { id: 250, name: 'Stfu I Got Kids!', price: 57, collection: 'Graphic Tees', image: `/images/STFU%20I%20GOT%20KIDS%21.png` },
 { id: 251, name: 'Stfu I Got Kids 1', price: 58, collection: 'Graphic Tees', image: `/images/STFU%20I%20Got%20Kids%201.png` },
 { id: 252, name: 'Sarcasm Level Expert', price: 59, collection: 'Graphic Tees', image: `/images/Sarcasm%20Level%20Expert.png` },
 { id: 253, name: 'Savage (Lion)', price: 18, collection: 'Graphic Tees', image: `/images/Savage%20%28Lion%29.png` },
 { id: 254, name: 'Sentimental Mother’S', price: 19, collection: 'Graphic Tees', image: `/images/Sentimental%20Mother%E2%80%99s.png` },
 { id: 255, name: 'Serpent Of Silent Screaming', price: 20, collection: 'Graphic Tees', image: `/images/Serpent%20of%20Silent%20Screaming.png` },
 { id: 256, name: 'Serpent Of Silent Screaming', price: 21, collection: 'Graphic Tees', image: `/images/Serpent%20of%20Silent%20Screaming.webp` },
 { id: 257, name: 'She Believed, She Did It All', price: 22, collection: 'Graphic Tees', image: `/images/She%20believed%2C%20she%20did%20it%20all.png` },
 { id: 258, name: 'She Is Strength, Grace, And Savage', price: 23, collection: 'Graphic Tees', image: `/images/She%20is%20strength%2C%20grace%2C%20and%20savage.png` },
 { id: 259, name: 'Shooting Stars', price: 24, collection: 'Graphic Tees', image: `/images/Shooting%20Stars.png` },
 { id: 260, name: 'Silly Dolphins – Splash Into Fun', price: 25, collection: 'Graphic Tees', image: `/images/Silly%20Dolphins%20%E2%80%93%20Splash%20into%20Fun.png` },
 { id: 261, name: 'Skull Head', price: 26, collection: 'Graphic Tees', image: `/images/Skull%20head.png` },
 { id: 262, name: 'Skunk Of Social Overstimulation', price: 27, collection: 'Graphic Tees', image: `/images/Skunk%20of%20Social%20Overstimulation.png` },
 { id: 263, name: 'Skunk Of Social Overstimulation', price: 28, collection: 'Graphic Tees', image: `/images/Skunk%20of%20Social%20Overstimulation.webp` },
 { id: 264, name: 'Sloth In Procrastination Mode', price: 29, collection: 'Graphic Tees', image: `/images/Sloth%20in%20procrastination%20mode.png` },
 { id: 265, name: 'Snail Of Slow‑Burn Resentment', price: 30, collection: 'Graphic Tees', image: `/images/Snail%20of%20Slow%E2%80%91Burn%20Resentment.png` },
 { id: 266, name: 'Snail Of Slow‑Burn Resentment', price: 31, collection: 'Graphic Tees', image: `/images/Snail%20of%20Slow%E2%80%91Burn%20Resentment.webp` },
 { id: 267, name: 'Soft Life Bundle Video', price: 32, collection: 'Graphic Tees', image: `/images/Soft%20Life%20Bundle%20video.jpg` },
 { id: 268, name: 'Soft Life Bundle', price: 33, collection: 'Graphic Tees', image: `/images/Soft%20Life%20Bundle.webp` },
 { id: 269, name: 'Space Octopus – Reach For The Stars!', price: 34, collection: 'Graphic Tees', image: `/images/Space%20Octopus%20%E2%80%93%20Reach%20for%20the%20Stars%21.png` },
 { id: 270, name: 'Spectrum Cry', price: 35, collection: 'Graphic Tees', image: `/images/Spectrum%20Cry.png` },
 { id: 271, name: 'Spiral Dreamscape', price: 36, collection: 'Graphic Tees', image: `/images/Spiral%20Dreamscape.png` },
 { id: 272, name: 'Spirit Of The Forest', price: 37, collection: 'Graphic Tees', image: `/images/Spirit%20of%20the%20Forest.png` },
 { id: 273, name: 'Squirrel Of Scattered Sanity', price: 38, collection: 'Graphic Tees', image: `/images/Squirrel%20of%20Scattered%20Sanity.png` },
 { id: 274, name: 'Squirrel Of Scattered Sanity1', price: 39, collection: 'Graphic Tees', image: `/images/Squirrel%20of%20Scattered%20sanity1.png` },
 { id: 275, name: 'Squirrel Of Chaotic Energy', price: 40, collection: 'Graphic Tees', image: `/images/Squirrel%20of%20chaotic%20energy.png` },
 { id: 276, name: 'Stardust And Dreams', price: 41, collection: 'Graphic Tees', image: `/images/Stardust%20and%20Dreams.png` },
 { id: 277, name: 'Stardust And Dreams (1)', price: 42, collection: 'Graphic Tees', image: `/images/Stardust%20and%20dreams%20%281%29.png` },
 { id: 278, name: 'Starlight And Shadow', price: 43, collection: 'Graphic Tees', image: `/images/Starlight%20and%20Shadow.png` },
 { id: 279, name: 'Stay Cool (Orange)', price: 44, collection: 'Graphic Tees', image: `/images/Stay%20Cool%20%28ORANGE%29.png` },
 { id: 280, name: 'Stay Cool (Purple)', price: 45, collection: 'Graphic Tees', image: `/images/Stay%20Cool%20%28PURPLE%29.png` },
 { id: 281, name: 'Strong, Kind, Fierce Mom Power', price: 46, collection: 'Graphic Tees', image: `/images/Strong%2C%20kind%2C%20fierce%20mom%20power.png` },
 { id: 282, name: 'Sunami House', price: 47, collection: 'Graphic Tees', image: `/images/Sunami%20House.png` },
 { id: 283, name: 'Superhero Mom In Crayon', price: 48, collection: 'Graphic Tees', image: `/images/Superhero%20mom%20in%20crayon.png` },
 { id: 284, name: 'Superheroes Wear Aprons Too', price: 49, collection: 'Graphic Tees', image: `/images/Superheroes%20wear%20aprons%20too.png` },
 { id: 285, name: 'Supermom  Love, Chaos, And Cozy Moments', price: 50, collection: 'Graphic Tees', image: `/images/Supermom_%20love%2C%20chaos%2C%20and%20cozy%20moments.png` },
 { id: 286, name: 'Temptation & Betrayal', price: 51, collection: 'Graphic Tees', image: `/images/TEMPTATION%20%26%20BETRAYAL.png` },
 { id: 287, name: 'Take The Leap', price: 52, collection: 'Graphic Tees', image: `/images/Take%20The%20Leap.png` },
 { id: 288, name: 'Thanks For Teaching Me Everything… Except How To Be Quiet', price: 53, collection: 'Graphic Tees', image: `/images/Thanks%20for%20Teaching%20Me%20Everything%E2%80%A6%20Except%20How%20to%20Be%20Quiet.png` },
 { id: 289, name: 'They See Me Mowin', price: 54, collection: 'Graphic Tees', image: `/images/They%20See%20Me%20Mowin.png` },
 { id: 290, name: 'Think Rich ', price: 55, collection: 'Graphic Tees', image: `/images/Think%20Rich%20.png` },
 { id: 291, name: 'Tiger Of Time Blindness', price: 56, collection: 'Graphic Tees', image: `/images/Tiger%20of%20Time-Blindness.png` },
 { id: 292, name: 'Tiger Of Time‑Blindness', price: 57, collection: 'Graphic Tees', image: `/images/Tiger%20of%20Time%E2%80%91Blindness.webp` },
 { id: 293, name: 'Timeless Treasures', price: 58, collection: 'Graphic Tees', image: `/images/Timeless%20Treasures.png` },
 { id: 294, name: 'Toddler Tornado', price: 59, collection: 'Graphic Tees', image: `/images/Toddler%20Tornado.png` },
 { id: 295, name: 'Tower Of Light ', price: 18, collection: 'Graphic Tees', image: `/images/Tower%20of%20Light%20.png` },
 { id: 296, name: 'Triangle Burst', price: 19, collection: 'Graphic Tees', image: `/images/Triangle%20Burst.png` },
 { id: 297, name: 'True Power', price: 20, collection: 'Graphic Tees', image: `/images/True%20Power.PNG` },
 { id: 298, name: 'Trust The Process', price: 21, collection: 'Graphic Tees', image: `/images/Trust%20the%20Process.png` },
 { id: 299, name: 'Turtle Of Tech Support Fatigue', price: 22, collection: 'Graphic Tees', image: `/images/Turtle%20of%20Tech%20Support%20Fatigue.png` },
 { id: 300, name: 'Turtle Of Tech Support Fatigue', price: 23, collection: 'Graphic Tees', image: `/images/Turtle%20of%20Tech%20Support%20Fatigue.webp` },
 { id: 301, name: 'Unfiltered Mama', price: 24, collection: 'Graphic Tees', image: `/images/Unfiltered%20Mama.png` },
 { id: 302, name: 'Unicorn Queen', price: 25, collection: 'Graphic Tees', image: `/images/Unicorn%20Queen.png` },
 { id: 303, name: 'Unicorn Of Unpaid Emotional Labor', price: 26, collection: 'Graphic Tees', image: `/images/Unicorn%20of%20Unpaid%20Emotional%20Labor.png` },
 { id: 304, name: 'Unicorn Of Unpaid Emotional Labor ', price: 27, collection: 'Graphic Tees', image: `/images/Unicorn%20of%20unpaid%20emotional%20labor%20.png` },
 { id: 305, name: 'Unshaken By Shadows', price: 28, collection: 'Graphic Tees', image: `/images/Unshaken%20by%20Shadows.png` },
 { id: 306, name: 'Virtue And Vice  ', price: 29, collection: 'Graphic Tees', image: `/images/Virtue%20and%20Vice%20%20.png` },
 { id: 307, name: 'Vivid Eye', price: 30, collection: 'Graphic Tees', image: `/images/Vivid%20Eye.png` },
 { id: 308, name: 'When Life Gets Ruff Just Paws And Light Up!', price: 31, collection: 'Graphic Tees', image: `/images/WHEN%20LIFE%20GETS%20RUFF%20JUST%20PAWS%20AND%20LIGHT%20UP%21.png` },
 { id: 309, name: 'Who Did This ', price: 32, collection: 'Graphic Tees', image: `/images/WHO%20DID%20THIS%20.png` },
 { id: 310, name: 'Who Did This ', price: 33, collection: 'Graphic Tees', image: `/images/WHO%20DID%20THIS%20.webp` },
 { id: 311, name: 'Well Shit', price: 34, collection: 'Graphic Tees', image: `/images/Well%20Shit.png` },
 { id: 312, name: 'Well Shit', price: 35, collection: 'Graphic Tees', image: `/images/Well%20Shit.webp` },
 { id: 313, name: 'When Life Gets Ruff Just Paws And Light Up', price: 36, collection: 'Graphic Tees', image: `/images/When%20life%20gets%20ruff%20just%20paws%20and%20light%20up.png` },
 { id: 314, name: 'Wild Ember Flower', price: 37, collection: 'Graphic Tees', image: `/images/Wild%20Ember%20Flower.png` },
 { id: 315, name: 'Woman In Rain', price: 38, collection: 'Graphic Tees', image: `/images/Woman%20in%20rain.png` },
 { id: 316, name: 'Wonder And Will', price: 39, collection: 'Graphic Tees', image: `/images/Wonder%20and%20Will.png` },
 { id: 317, name: 'Wonder Flows Without End', price: 40, collection: 'Graphic Tees', image: `/images/Wonder%20flows%20without%20end.png` },
 { id: 318, name: 'World’S Okayest Dad (But Still A Legend)', price: 41, collection: 'Graphic Tees', image: `/images/World%E2%80%99s%20Okayest%20Dad%20%28But%20Still%20a%20Legend%29.png` },
 { id: 319, name: 'You’Re Grill Ious, Dad!', price: 42, collection: 'Graphic Tees', image: `/images/You%E2%80%99re%20Grill-ious%2C%20Dad%21.png` },
 { id: 320, name: 'You’Re The Coolest Dad This Side Of The Grill', price: 43, collection: 'Graphic Tees', image: `/images/You%E2%80%99re%20the%20Coolest%20Dad%20This%20Side%20of%20the%20Grill.png` },
 { id: 321, name: 'Zero Fucks Given ', price: 44, collection: 'Graphic Tees', image: `/images/Zero%20Fucks%20Given%20.png` },
 { id: 322, name: 'Zero Fucks Given', price: 45, collection: 'Graphic Tees', image: `/images/Zero%20Fucks%20Given.webp` },
 { id: 323, name: 'Zodiac Women', price: 46, collection: 'Graphic Tees', image: `/images/Zodiac%20Women.png` },
 { id: 324, name: ' Behind Every Great Kid', price: 47, collection: 'Graphic Tees', image: `/images/_BEHIND%20EVERY%20GREAT%20KID.png` },
 { id: 325, name: 'Beetlejuice Its Showtime (Green)', price: 48, collection: 'Graphic Tees', image: `/images/beetlejuice%20its%20showtime%20%28green%29.png` },
 { id: 326, name: 'Beetljuice Its Showtime (Green Orange)', price: 49, collection: 'Graphic Tees', image: `/images/beetljuice%20Its%20showtime%20%28green%20orange%29.png` },
 { id: 327, name: 'Chines Lunar Girl', price: 50, collection: 'Graphic Tees', image: `/images/chines-lunar%20girl.png` },
 { id: 328, name: 'Chinese Lunar Day', price: 51, collection: 'Graphic Tees', image: `/images/chinese%20lunar%20day.png` },
 { id: 329, name: 'Chinese  Cherry Blossom Tiger', price: 52, collection: 'Graphic Tees', image: `/images/chinese-%20cherry%20blossom%20tiger.png` },
 { id: 330, name: 'Chinese  Girl Print', price: 53, collection: 'Graphic Tees', image: `/images/chinese-%20girl%20print.png` },
 { id: 331, name: 'Chinese  Goldfish Flowers', price: 54, collection: 'Graphic Tees', image: `/images/chinese-%20goldfish%20flowers.png` },
 { id: 332, name: 'Chinese  Tiger', price: 55, collection: 'Graphic Tees', image: `/images/chinese-%20tiger.png` },
 { id: 333, name: 'Chinese Tiger Master', price: 56, collection: 'Graphic Tees', image: `/images/chinese-tiger%20master.png` },
 { id: 334, name: 'Faith Hope Cure Print', price: 57, collection: 'Graphic Tees', image: `/images/faith%20hope%20cure%20print.png` },
 { id: 335, name: 'Flamingo Flock You Cancer Print', price: 58, collection: 'Graphic Tees', image: `/images/flamingo-flock%20you%20cancer%20print.png` },
 { id: 336, name: 'Ghost Heart Print', price: 59, collection: 'Graphic Tees', image: `/images/ghost%20heart%20print.png` },
 { id: 337, name: 'Give Cance The Boot Print', price: 18, collection: 'Graphic Tees', image: `/images/give%20cance%20the%20boot%20print.png` },
 { id: 338, name: 'Her Fight Is My Fight', price: 19, collection: 'Graphic Tees', image: `/images/her%20fight%20is%20my%20fight.png` },
 { id: 339, name: 'Lunar  Dragon', price: 20, collection: 'Graphic Tees', image: `/images/lunar-%20dragon.png` },
 { id: 340, name: 'Lunar  Gold Fish', price: 21, collection: 'Graphic Tees', image: `/images/lunar-%20gold%20fish.png` },
 { id: 341, name: 'Lunar  Hats', price: 22, collection: 'Trucker Hats', image: `/images/lunar-%20hats.png` },
 { id: 342, name: 'Manifesting', price: 23, collection: 'Graphic Tees', image: `/images/manifesting.png` },
 { id: 343, name: 'Mimis Cozy Corner White Logo', price: 24, collection: 'Graphic Tees', image: `/images/mimis_cozy_corner_White%20logo.webp` },
 { id: 344, name: 'Mimis Cozy Corner Ad Asset Youtube', price: 25, collection: 'Graphic Tees', image: `/images/mimis_cozy_corner_ad_asset-YouTube.png` },
 { id: 345, name: 'Mimis Cozy Corner Magenta', price: 26, collection: 'Graphic Tees', image: `/images/mimis_cozy_corner_magenta.webp` },
 { id: 346, name: 'Open Minded', price: 27, collection: 'Graphic Tees', image: `/images/open%20minded.png` },
 { id: 347, name: 'Pasted File 0Efu1U Believe In Yourself (Bright)', price: 28, collection: 'Graphic Tees', image: `/images/pasted_file_0eFU1u_BELIEVE%20IN%20YOURSELF%20%28BRIGHT%29.webp` },
 { id: 348, name: 'Pasted File 13I6Mw Wild Ember Flower', price: 29, collection: 'Graphic Tees', image: `/images/pasted_file_13i6mw_Wild%20Ember%20Flower.png` },
 { id: 349, name: 'Pasted File 1L9Ccz Mom Life  Fueled By Love And Coffee', price: 30, collection: 'Graphic Tees', image: `/images/pasted_file_1L9CCz_Mom%20life_%20fueled%20by%20love%20and%20coffee.png` },
 { id: 350, name: 'Pasted File 1Jqdro Burnt Out Crispy Unicorn', price: 31, collection: 'Graphic Tees', image: `/images/pasted_file_1jQDRO_BURNT%20OUT%20CRISPY%20UNICORN.webp` },
 { id: 351, name: 'Pasted File 1Xfurc Healing In Progress (Glow) ', price: 32, collection: 'Graphic Tees', image: `/images/pasted_file_1xfurc_HEALING%20in%20PROGRESS%20%28GLOW%29%20.png` },
 { id: 352, name: 'Pasted File 2Xbr4T Manifesting', price: 33, collection: 'Graphic Tees', image: `/images/pasted_file_2XbR4T_manifesting.png` },
 { id: 353, name: 'Pasted File 34Yzaq Soft Life Bundle Video', price: 34, collection: 'Graphic Tees', image: `/images/pasted_file_34YzAq_Soft%20Life%20Bundle%20video.jpg` },
 { id: 354, name: 'Pasted File 3Psbuw Healing In Progress (Bright)', price: 35, collection: 'Graphic Tees', image: `/images/pasted_file_3PSbUw_HEALING%20IN%20PROGRESS%20%28BRIGHT%29.webp` },
 { id: 355, name: 'Pasted File 3Ycc64 Goat Of Grunt‑Based Communication', price: 36, collection: 'Graphic Tees', image: `/images/pasted_file_3Ycc64_Goat%20of%20Grunt%E2%80%91Based%20Communication.webp` },
 { id: 356, name: 'Pasted File 3Ii3Y8 Healing In Progress (Calm)', price: 37, collection: 'Graphic Tees', image: `/images/pasted_file_3ii3y8_HEALING%20IN%20PROGRESS%20%28CALM%29.webp` },
 { id: 357, name: 'Pasted File 3Lmfi4 Bear Of Backyard Avoidance', price: 38, collection: 'Graphic Tees', image: `/images/pasted_file_3lmfi4_BEAR%20OF%20BACKYARD%20AVOIDANCE.webp` },
 { id: 358, name: 'Pasted File 45Rd4P Kindness Bear – Be Kind, Be Brave ', price: 39, collection: 'Graphic Tees', image: `/images/pasted_file_45rd4P_Kindness%20Bear%20%E2%80%93%20Be%20Kind%2C%20Be%20Brave%20.png` },
 { id: 359, name: 'Pasted File 4Btck8 Heaven And Havoc ', price: 40, collection: 'Graphic Tees', image: `/images/pasted_file_4bTcK8_Heaven%20and%20Havoc%20.webp` },
 { id: 360, name: 'Pasted File 4Zekeu Healing In Progress (Plain)', price: 41, collection: 'Graphic Tees', image: `/images/pasted_file_4zeKeU_HEALING%20IN%20PROGRESS%20%28PLAIN%29.webp` },
 { id: 361, name: 'Pasted File 57Hw0K High Hound', price: 42, collection: 'Graphic Tees', image: `/images/pasted_file_57HW0K_High%20Hound.png` },
 { id: 362, name: 'Pasted File 5J1R51 Locked Dove', price: 43, collection: 'Graphic Tees', image: `/images/pasted_file_5J1R51_Locked%20Dove.png` },
 { id: 363, name: 'Pasted File 5Ss5X9 Mom, The Ultimate Search Engine', price: 44, collection: 'Graphic Tees', image: `/images/pasted_file_5ss5x9_Mom%2C%20the%20ultimate%20search%20engine.png` },
 { id: 364, name: 'Pasted File 679X3D I Survied To Many Storms To Be Bothered By Raindrops', price: 45, collection: 'Graphic Tees', image: `/images/pasted_file_679x3d_I%20survied%20to%20many%20storms%20to%20be%20bothered%20by%20raindrops.png` },
 { id: 365, name: 'Pasted File 6Th5Va Angels & Outlaws', price: 46, collection: 'Graphic Tees', image: `/images/pasted_file_6Th5VA_ANGELS%20%26%20OUTLAWS.webp` },
 { id: 366, name: 'Pasted File 89Whxx Done Dragon', price: 47, collection: 'Graphic Tees', image: `/images/pasted_file_89WhXX_DONE%20DRAGON.webp` },
 { id: 367, name: 'Pasted File 8Jdl0A God Sent Kids And Blessings', price: 48, collection: 'Graphic Tees', image: `/images/pasted_file_8jDL0a_God-sent%20kids%20and%20blessings.png` },
 { id: 368, name: 'Pasted File 9Himni Lion Of Lost Tools', price: 49, collection: 'Graphic Tees', image: `/images/pasted_file_9HImNi_Lion%20of%20Lost%20Tools.png` },
 { id: 369, name: 'Pasted File 9Qeod4 Highway Tower  (1000 X 1000 Px)', price: 50, collection: 'Graphic Tees', image: `/images/pasted_file_9QeOd4_Highway%20Tower%20%20%281000%20x%201000%20px%29.png` },
 { id: 370, name: 'Pasted File 9Sq7An Cozy Reader Club (Plain)', price: 51, collection: 'Graphic Tees', image: `/images/pasted_file_9SQ7aN_COZY%20READER%20CLUB%20%28PLAIN%29.webp` },
 { id: 371, name: 'Pasted File 9Lvwc1 Kindness Bear – Be Kind, Be Brave', price: 52, collection: 'Graphic Tees', image: `/images/pasted_file_9lvWC1_Kindness%20Bear%20%E2%80%93%20Be%20Kind%2C%20Be%20Brave.webp` },
 { id: 372, name: 'Pasted File Aeznva Dads Dance Moves', price: 53, collection: 'Graphic Tees', image: `/images/pasted_file_AEzNvA_DADS%20DANCE%20MOVES.webp` },
 { id: 373, name: 'Pasted File An4Reg Superheroes Wear Aprons Too', price: 54, collection: 'Graphic Tees', image: `/images/pasted_file_An4REg_Superheroes%20wear%20aprons%20too.png` },
 { id: 374, name: 'Pasted File Cm1Lfg Monkey Of Mental Load Mayhem', price: 55, collection: 'Graphic Tees', image: `/images/pasted_file_Cm1lfG_Monkey%20of%20Mental%20Load%20Mayhem.webp` },
 { id: 375, name: 'Pasted File D80Ehp Messy Mom Life Fueled By Faith', price: 56, collection: 'Graphic Tees', image: `/images/pasted_file_D80Ehp_Messy%20mom%20life%20fueled%20by%20faith.png` },
 { id: 376, name: 'Pasted File Dggqmu Mom Boss Vibes In Full Force', price: 57, collection: 'Graphic Tees', image: `/images/pasted_file_DGGQmU_Mom%20boss%20vibes%20in%20full%20force.png` },
 { id: 377, name: 'Pasted File Dggyrj Screenshot 2024 06 07 133310(Saved)', price: 58, collection: 'Graphic Tees', image: `/images/pasted_file_DGgyrJ_Screenshot%202024-06-07%20133310%28Saved%29.png` },
 { id: 378, name: 'Pasted File Dx5Agm Believe In Yourself (Night)', price: 59, collection: 'Graphic Tees', image: `/images/pasted_file_Dx5agM_BELIEVE%20IN%20YOURSELF%20%28NIGHT%29.webp` },
 { id: 379, name: 'Pasted File Ekb36R Wild Ember Flower (765 X 780 Px)', price: 18, collection: 'Graphic Tees', image: `/images/pasted_file_Ekb36R_Wild%20Ember%20Flower%20%28765%20x%20780%20px%29.png` },
 { id: 380, name: 'Pasted File Ekus3F Parenting Demon Mode', price: 19, collection: 'Graphic Tees', image: `/images/pasted_file_EkuS3f_Parenting%20Demon%20Mode.jpg` },
 { id: 381, name: 'Pasted File Espkt7 Professional Snack Provider, Boo Boo Fixer', price: 20, collection: 'Graphic Tees', image: `/images/pasted_file_EsPkt7_Professional%20snack%20provider%2C%20boo%20boo%20fixer.png` },
 { id: 382, name: 'Pasted File F933Gp I Am Confident', price: 21, collection: 'Graphic Tees', image: `/images/pasted_file_F933gp_I%20AM%20CONFIDENT.png` },
 { id: 383, name: 'Pasted File Fxpmug Lunar  Dragon', price: 22, collection: 'Graphic Tees', image: `/images/pasted_file_FxpmuG_lunar-%20dragon.png` },
 { id: 384, name: 'Pasted File Go6Cqx Motherhood Chaos  Fueled By Love And Coffee', price: 23, collection: 'Graphic Tees', image: `/images/pasted_file_GO6CqX_Motherhood%20chaos_%20fueled%20by%20love%20and%20coffee.png` },
 { id: 385, name: 'Pasted File Gy0Hk7 Hypno Fusion Petal', price: 24, collection: 'Graphic Tees', image: `/images/pasted_file_GY0Hk7_Hypno%20Fusion%20Petal.png` },
 { id: 386, name: 'Pasted File H0Img0 Lion Of Lost Tools', price: 25, collection: 'Graphic Tees', image: `/images/pasted_file_H0imG0_Lion%20of%20Lost%20Tools.webp` },
 { id: 387, name: 'Pasted File Haiunu Toddler Tornado', price: 26, collection: 'Graphic Tees', image: `/images/pasted_file_HAiunU_Toddler%20Tornado.png` },
 { id: 388, name: 'Pasted File I872Jz Vivid Eye', price: 27, collection: 'Graphic Tees', image: `/images/pasted_file_I872jz_Vivid%20Eye.png` },
 { id: 389, name: 'Pasted File Icof29 Mama Bear And Her Cubs', price: 28, collection: 'Graphic Tees', image: `/images/pasted_file_ICof29_Mama%20bear%20and%20her%20cubs.png` },
 { id: 390, name: 'Pasted File Il8Wce Echoes Of The Ascendant Stone', price: 29, collection: 'Graphic Tees', image: `/images/pasted_file_IL8WCE_Echoes%20of%20the%20Ascendant%20Stone.png` },
 { id: 391, name: 'Pasted File Ivwr3D Lightening Fights', price: 30, collection: 'Graphic Tees', image: `/images/pasted_file_Ivwr3D_Lightening%20Fights.PNG` },
 { id: 392, name: 'Pasted File Jdlsjl Mentally At Home', price: 31, collection: 'Graphic Tees', image: `/images/pasted_file_JDlsjL_Mentally%20at%20Home.png` },
 { id: 393, name: 'Pasted File Jjivpd Mom Boss Vibes In Full Force', price: 32, collection: 'Graphic Tees', image: `/images/pasted_file_JJiVPD_Mom%20boss%20vibes%20in%20full%20force.png` },
 { id: 394, name: 'Pasted File Jkwne3 Messy Mom Life  Fueled By Faith', price: 33, collection: 'Graphic Tees', image: `/images/pasted_file_JKwNe3_Messy%20mom%20life_%20fueled%20by%20faith.png` },
 { id: 395, name: 'Pasted File Jsnajr Just One More Chapter', price: 34, collection: 'Graphic Tees', image: `/images/pasted_file_JSnajr_JUST%20ONE%20MORE%20CHAPTER.png` },
 { id: 396, name: 'Pasted File Jc8O6O Lunar  Hats', price: 35, collection: 'Trucker Hats', image: `/images/pasted_file_Jc8O6o_lunar-%20hats.png` },
 { id: 397, name: 'Pasted File Kn9Zrm Lust And Loyalty', price: 36, collection: 'Graphic Tees', image: `/images/pasted_file_KN9zrm_Lust%20and%20Loyalty.png` },
 { id: 398, name: 'Pasted File Kwv5Ja Mama Needs Wine And Survival', price: 37, collection: 'Graphic Tees', image: `/images/pasted_file_KWV5jA_Mama%20needs%20wine%20and%20survival.png` },
 { id: 399, name: 'Pasted File Lmqevb Mom At 2 Percent', price: 38, collection: 'Graphic Tees', image: `/images/pasted_file_LmQeVB_Mom%20at%202%20Percent.png` },
 { id: 400, name: 'Pasted File Lwi3Pt Dog Of Dad Jokes', price: 39, collection: 'Graphic Tees', image: `/images/pasted_file_Lwi3pt_DOG%20OF%20DAD%20JOKES.webp` },
 { id: 401, name: 'Pasted File M8S2Hu Mom Life In Full Swing', price: 40, collection: 'Graphic Tees', image: `/images/pasted_file_M8s2Hu_Mom%20life%20in%20full%20swing.png` },
 { id: 402, name: 'Pasted File Meqfoy Mom The Original Sea', price: 41, collection: 'Graphic Tees', image: `/images/pasted_file_MEQfOy_Mom%20The%20Original%20Sea.png` },
 { id: 403, name: 'Pasted File Mlxelb Live Free Image', price: 42, collection: 'Graphic Tees', image: `/images/pasted_file_MLxElB_Live%20Free%20Image.png` },
 { id: 404, name: 'Pasted File N5Ej5R Bookish', price: 43, collection: 'Graphic Tees', image: `/images/pasted_file_N5EJ5R_BOOKISH.webp` },
 { id: 405, name: 'Pasted File Navupe Lust And Loyalty', price: 44, collection: 'Graphic Tees', image: `/images/pasted_file_NAVUPE_Lust%20and%20Loyalty.webp` },
 { id: 406, name: 'Pasted File Nbspih Lizard Of Lawn Obsession', price: 45, collection: 'Graphic Tees', image: `/images/pasted_file_NbSPIH_Lizard%20of%20lawn%20obsession.webp` },
 { id: 407, name: 'Pasted File Ngvcbt Bold And Unfiltered Expression', price: 46, collection: 'Graphic Tees', image: `/images/pasted_file_NgVcbT_Bold%20and%20unfiltered%20expression.png` },
 { id: 408, name: 'Pasted File Nn38Wn Light In The Sky', price: 47, collection: 'Graphic Tees', image: `/images/pasted_file_Nn38wN_Light%20in%20the%20Sky.PNG` },
 { id: 409, name: 'Pasted File O0Rwbv Mentally At Home', price: 48, collection: 'Graphic Tees', image: `/images/pasted_file_O0RwbV_Mentally%20at%20Home.webp` },
 { id: 410, name: 'Pasted File Oih4J1 Hippo Of Half‑Finished Projects', price: 49, collection: 'Graphic Tees', image: `/images/pasted_file_OIH4j1_Hippo%20of%20Half%E2%80%91Finished%20Projects.png` },
 { id: 411, name: 'Pasted File Offtjm Mama Needs Wine And Survival', price: 50, collection: 'Graphic Tees', image: `/images/pasted_file_OfFtjM_Mama%20needs%20wine%20and%20survival.png` },
 { id: 412, name: 'Pasted File Pxuiwl Motherhood  The Toughest Job, Powered By Love', price: 51, collection: 'Graphic Tees', image: `/images/pasted_file_PxuiWL_Motherhood_%20the%20toughest%20job%2C%20powered%20by%20love.png` },
 { id: 413, name: 'Pasted File Qpkt5Q Octopus Of Overcommitment', price: 52, collection: 'Graphic Tees', image: `/images/pasted_file_QPKt5q_Octopus%20of%20Overcommitment.webp` },
 { id: 414, name: 'Pasted File Qrtnfl Lizard Of Lawn Obsession', price: 53, collection: 'Graphic Tees', image: `/images/pasted_file_QRtnFL_Lizard%20of%20lawn%20obsession.png` },
 { id: 415, name: 'Pasted File Qazpjq Believe In Yourself (Dreamy)', price: 54, collection: 'Graphic Tees', image: `/images/pasted_file_QazpJq_BELIEVE%20IN%20YOURSELF%20%28DREAMY%29.webp` },
 { id: 416, name: 'Pasted File Racyh3 Fierce Vibrance Adult Halloween Edition 2 Cover Page Edited', price: 55, collection: 'Graphic Tees', image: `/images/pasted_file_RacyH3_Fierce%20Vibrance%20adult%20Halloween%20EDITION%202%20COVER%20PAGE_edited.png` },
 { id: 417, name: 'Pasted File Rwuds7 Adventure Awaits', price: 56, collection: 'Graphic Tees', image: `/images/pasted_file_RwUdS7_ADVENTURE%20AWAITS.webp` },
 { id: 418, name: 'Pasted File Sh5Vav First My Mother, Forever My Friend', price: 57, collection: 'Graphic Tees', image: `/images/pasted_file_SH5vaV_First%20my%20mother%2C%20forever%20my%20friend.png` },
 { id: 419, name: 'Pasted File Sar20W Hedgehog’S Guide To Social Anxiety', price: 58, collection: 'Graphic Tees', image: `/images/pasted_file_Sar20W_Hedgehog%E2%80%99s%20guide%20to%20social%20anxiety.png` },
 { id: 420, name: 'Pasted File Svyn8U Mom Fuel And Toddler Chaos', price: 59, collection: 'Graphic Tees', image: `/images/pasted_file_SvyN8u_Mom%20fuel%20and%20toddler%20chaos.png` },
 { id: 421, name: 'Pasted File Twdhzw Heaven And Havoc ', price: 18, collection: 'Graphic Tees', image: `/images/pasted_file_TwDHZW_Heaven%20and%20Havoc%20.png` },
 { id: 422, name: 'Pasted File Tzrejh Calm Mind Club (Cozy)', price: 19, collection: 'Graphic Tees', image: `/images/pasted_file_TzReJH_CALM%20MIND%20CLUB%20%28COZY%29.webp` },
 { id: 423, name: 'Pasted File Uczary Choose Calm (Plain)', price: 20, collection: 'Graphic Tees', image: `/images/pasted_file_UcZaRY_CHOOSE%20CALM%20%28PLAIN%29.webp` },
 { id: 424, name: 'Pasted File Vfasxa Mom Fuel And Toddler Chaos', price: 21, collection: 'Graphic Tees', image: `/images/pasted_file_VFasXA_Mom%20fuel%20and%20toddler%20chaos.png` },
 { id: 425, name: 'Pasted File Vuhqd6 Calm Mind Club (Plain)', price: 22, collection: 'Graphic Tees', image: `/images/pasted_file_VuHqD6_CALM%20MIND%20CLUB%20%28PLAIN%29.webp` },
 { id: 426, name: 'Pasted File W3Xhao Happy Dino Trio – Let’S Play!', price: 23, collection: 'Graphic Tees', image: `/images/pasted_file_W3xhAo_Happy%20Dino%20Trio%20%E2%80%93%20Let%E2%80%99s%20Play%21.webp` },
 { id: 427, name: 'Pasted File Wwmagn Octopus Of Overcommitment 2', price: 24, collection: 'Graphic Tees', image: `/images/pasted_file_WwMAgN_Octopus%20of%20Overcommitment%202.webp` },
 { id: 428, name: 'Pasted File X8Yxns Mom The Original Sea', price: 25, collection: 'Graphic Tees', image: `/images/pasted_file_X8yxns_Mom%20The%20Original%20Sea.png` },
 { id: 429, name: 'Pasted File Xkw2Xw Highway Tower  ', price: 26, collection: 'Graphic Tees', image: `/images/pasted_file_XKw2xW_Highway%20Tower%20%20.png` },
 { id: 430, name: 'Pasted File Xfravz Moose Of Miscommunication', price: 27, collection: 'Graphic Tees', image: `/images/pasted_file_XfRAvz_Moose%20of%20Miscommunication.webp` },
 { id: 431, name: 'Pasted File Xjmfzj Goat Of Grocery Rage', price: 28, collection: 'Graphic Tees', image: `/images/pasted_file_XjmfZJ_Goat%20of%20Grocery%20Rage.webp` },
 { id: 432, name: 'Pasted File Xrq8An Coyote Car Ride Commentary', price: 29, collection: 'Graphic Tees', image: `/images/pasted_file_Xrq8aN_COYOTE%20CAR-RIDE%20COMMENTARY.webp` },
 { id: 433, name: 'Pasted File Yr15El Healing In Progress (Plain) ', price: 30, collection: 'Graphic Tees', image: `/images/pasted_file_YR15El_HEALING%20in%20PROGRESS%20%28PLAIN%29%20.png` },
 { id: 434, name: 'Pasted File Zug0L5 Mindful Zen Bath', price: 31, collection: 'Graphic Tees', image: `/images/pasted_file_ZUG0L5_Mindful%20Zen%20Bath.png` },
 { id: 435, name: 'Pasted File Zi0Cln Messy Mom Life  Fueled By Faith', price: 32, collection: 'Graphic Tees', image: `/images/pasted_file_Zi0CLN_Messy%20mom%20life_%20fueled%20by%20faith.png` },
 { id: 436, name: 'Pasted File Zjm8Yo Mama Needs Wine (Lucid Yellow)', price: 33, collection: 'Graphic Tees', image: `/images/pasted_file_Zjm8Yo_Mama%20Needs%20Wine%20%28Lucid-Yellow%29.png` },
 { id: 437, name: 'Pasted File A5Vhpc Choose Calm (Blue)', price: 34, collection: 'Graphic Tees', image: `/images/pasted_file_a5VhpC_CHOOSE%20CALM%20%28BLUE%29.webp` },
 { id: 438, name: 'Pasted File Arrg0Y Chaos & Crown', price: 35, collection: 'Graphic Tees', image: `/images/pasted_file_arRG0Y_CHAOS%20%26%20CROWN.webp` },
 { id: 439, name: 'Pasted File Btyucl Grim', price: 36, collection: 'Graphic Tees', image: `/images/pasted_file_bTYucL_GRIM.webp` },
 { id: 440, name: 'Pasted File Bokhuo Home Is Where Mom Is Loved', price: 37, collection: 'Graphic Tees', image: `/images/pasted_file_bokHuo_Home%20is%20where%20Mom%20is%20loved.png` },
 { id: 441, name: 'Pasted File Cchnlv Choose Calm (Zen)', price: 38, collection: 'Graphic Tees', image: `/images/pasted_file_cCHnlv_CHOOSE%20CALM%20%28ZEN%29.webp` },
 { id: 442, name: 'Pasted File Cpa6M0 Genie Of Gendered Expectations', price: 39, collection: 'Graphic Tees', image: `/images/pasted_file_cPa6m0_Genie%20of%20Gendered%20Expectations.webp` },
 { id: 443, name: 'Pasted File Cmzdaw Inner Self Pic', price: 40, collection: 'Graphic Tees', image: `/images/pasted_file_cmzDAw_Inner%20self%20pic.png` },
 { id: 444, name: 'Pasted File Dnmqqv Stay Calm 8X10', price: 41, collection: 'Graphic Tees', image: `/images/pasted_file_dnMqQv_STAY%20CALM%208X10.png` },
 { id: 445, name: 'Pasted File Eorack My Give A Damn’S Busted ', price: 42, collection: 'Graphic Tees', image: `/images/pasted_file_eORacK_My%20Give%20A%20Damn%E2%80%99s%20Busted%20.webp` },
 { id: 446, name: 'Pasted File Exuwxg Home Is Wherever Mom Is', price: 43, collection: 'Graphic Tees', image: `/images/pasted_file_exUWXg_Home%20is%20wherever%20mom%20is.png` },
 { id: 447, name: 'Pasted File F11Tv9 I Am The Storm', price: 44, collection: 'Graphic Tees', image: `/images/pasted_file_f11tv9_I%20am%20The%20Storm.png` },
 { id: 448, name: 'Pasted File Goamwb I Am Connected To The Divine', price: 45, collection: 'Graphic Tees', image: `/images/pasted_file_gOamwb_I%20am%20connected%20to%20the%20divine.png` },
 { id: 449, name: 'Pasted File Hpqlxt Make Something New', price: 46, collection: 'Graphic Tees', image: `/images/pasted_file_hpqLXt_Make%20something%20new.png` },
 { id: 450, name: 'Pasted File I21Dym Her Fight Is My Fight', price: 47, collection: 'Graphic Tees', image: `/images/pasted_file_i21DYM_her%20fight%20is%20my%20fight.png` },
 { id: 451, name: 'Pasted File Imrh2Z Buffalo Budgeting Breakdown', price: 48, collection: 'Graphic Tees', image: `/images/pasted_file_iMRh2Z_BUFFALO%20BUDGETING%20BREAKDOWN.webp` },
 { id: 452, name: 'Pasted File Iqo35B Insane Rat', price: 49, collection: 'Graphic Tees', image: `/images/pasted_file_iQo35b_Insane%20Rat.png` },
 { id: 453, name: 'Pasted File Innbo3 Lunar  Gold Fish', price: 50, collection: 'Graphic Tees', image: `/images/pasted_file_inNbO3_lunar-%20gold%20fish.png` },
 { id: 454, name: 'Pasted File Iqs5Og Cozy Reader Club 3', price: 51, collection: 'Graphic Tees', image: `/images/pasted_file_iqS5Og_COZY%20READER%20CLUB%203.webp` },
 { id: 455, name: 'Pasted File J3Nw35 Divine & Damned', price: 52, collection: 'Graphic Tees', image: `/images/pasted_file_j3NW35_DIVINE%20%26%20DAMNED.webp` },
 { id: 456, name: 'Pasted File Jmc3Sh Image', price: 53, collection: 'Graphic Tees', image: `/images/pasted_file_jMc3SH_image.png` },
 { id: 457, name: 'Pasted File Jtzmx6 Think Rich', price: 54, collection: 'Graphic Tees', image: `/images/pasted_file_jTzMX6_Think%20Rich.png` },
 { id: 458, name: 'Pasted File Jups6Y Mama Needs Wine (Lucid Yellow)', price: 55, collection: 'Graphic Tees', image: `/images/pasted_file_jUpS6Y_Mama%20Needs%20Wine%20%28lucid-yellow%29.png` },
 { id: 459, name: 'Pasted File Jsioww Cozy Reader Club (Cozy)', price: 56, collection: 'Graphic Tees', image: `/images/pasted_file_jsIOwW_COZY%20READER%20CLUB%20%28COZY%29.webp` },
 { id: 460, name: 'Pasted File K6Rhsu Professional Snack Provider And Boo Boo Fixer', price: 57, collection: 'Graphic Tees', image: `/images/pasted_file_k6RhSu_Professional%20snack%20provider%20and%20boo%20boo%20fixer.png` },
 { id: 461, name: 'Pasted File Koy80O Divine Light Within', price: 58, collection: 'Graphic Tees', image: `/images/pasted_file_koy80O_Divine%20Light%20Within.png` },
 { id: 462, name: 'Pasted File La4Od1 Calm Mind Club(Zen)', price: 59, collection: 'Graphic Tees', image: `/images/pasted_file_lA4OD1_CALM%20MIND%20CLUB%28ZEN%29.webp` },
 { id: 463, name: 'Pasted File Loclfs Casting Spells Not Opinions', price: 18, collection: 'Graphic Tees', image: `/images/pasted_file_loclfS_Casting%20Spells%20Not%20Opinions.png` },
 { id: 464, name: 'Pasted File Lootfq Chill Out (Colorful)', price: 19, collection: 'Graphic Tees', image: `/images/pasted_file_looTFq_CHILL%20OUT%20%28COLORFUL%29.webp` },
 { id: 465, name: 'Pasted File Lop5Fr I Am Strong', price: 20, collection: 'Graphic Tees', image: `/images/pasted_file_lop5Fr_I%20Am%20Strong.png` },
 { id: 466, name: 'Pasted File M97Try I Run On Coffee And Chaos', price: 21, collection: 'Graphic Tees', image: `/images/pasted_file_m97TRy_I%20run%20on%20coffee%20and%20chaos.png` },
 { id: 467, name: 'Pasted File Nyxo7U Mama Needs Wine (Lucid)', price: 22, collection: 'Graphic Tees', image: `/images/pasted_file_nYxo7u_Mama%20Needs%20Wine%20%28Lucid%29.png` },
 { id: 468, name: 'Pasted File Ozlmwf Mideviel Image', price: 23, collection: 'Graphic Tees', image: `/images/pasted_file_oZlmwf_Mideviel%20image.png` },
 { id: 469, name: 'Pasted File Op0G4I Spectrum Cry', price: 24, collection: 'Graphic Tees', image: `/images/pasted_file_op0G4I_Spectrum%20Cry.png` },
 { id: 470, name: 'Pasted File Q9Vcy8 My Dad Eats My Fries', price: 25, collection: 'Graphic Tees', image: `/images/pasted_file_q9vCY8_MY%20DAD%20EATS%20MY%20FRIES.webp` },
 { id: 471, name: 'Pasted File Qf2Upw Angels &Outlaws 2', price: 26, collection: 'Graphic Tees', image: `/images/pasted_file_qF2upW_ANGELS%20%26OUTLAWS%202.webp` },
 { id: 472, name: 'Pasted File Rmzca1 Healing In Progress (Glow)', price: 27, collection: 'Graphic Tees', image: `/images/pasted_file_rmzca1_HEALING%20IN%20PROGRESS%20%28GLOW%29.webp` },
 { id: 473, name: 'Pasted File Scdklk Unfiltered Mama Logo Design', price: 28, collection: 'Graphic Tees', image: `/images/pasted_file_sCDKlk_Unfiltered%20Mama%20logo%20design.png` },
 { id: 474, name: 'Pasted File Sbpqlf Mom At 2 Percent', price: 29, collection: 'Graphic Tees', image: `/images/pasted_file_sbpqLf_Mom%20at%202%20Percent.webp` },
 { id: 475, name: 'Pasted File Sipc9I Color Burst', price: 30, collection: 'Graphic Tees', image: `/images/pasted_file_siPC9I_Color%20Burst.webp` },
 { id: 476, name: 'Pasted File Svhdhz Mama Needs Wine (Lucid)', price: 31, collection: 'Graphic Tees', image: `/images/pasted_file_svHdHz_Mama%20Needs%20Wine%20%28lucid%29.png` },
 { id: 477, name: 'Pasted File Tdmhtj Stfu I Got Kids (1000 X 1000 Px)', price: 32, collection: 'Graphic Tees', image: `/images/pasted_file_tDmhTJ_STFU%20I%20Got%20Kids%20%281000%20x%201000%20px%29.png` },
 { id: 478, name: 'Pasted File Trcwfi I Embody The Power Of The Ancients', price: 33, collection: 'Graphic Tees', image: `/images/pasted_file_tRcwfi_I%20embody%20the%20power%20of%20the%20ancients.png` },
 { id: 479, name: 'Pasted File Tqo5Dl I Will Not Give Up My Power!', price: 34, collection: 'Graphic Tees', image: `/images/pasted_file_tqO5Dl_I%20will%20not%20give%20up%20my%20Power%21.png` },
 { id: 480, name: 'Pasted File Ucnl8V Tower Of Light (1000 X 1000 Px)', price: 35, collection: 'Graphic Tees', image: `/images/pasted_file_uCNL8v_Tower%20of%20Light%20%281000%20x%201000%20px%29.png` },
 { id: 481, name: 'Pasted File Uognnh She Is Strength, Grace, And Savage', price: 36, collection: 'Graphic Tees', image: `/images/pasted_file_uognnh_She%20is%20strength%2C%20grace%2C%20and%20savage.png` },
 { id: 482, name: 'Pasted File V0Ocrq Harmony (1000 X 1000 Px)', price: 37, collection: 'Graphic Tees', image: `/images/pasted_file_v0oCRq_Harmony%20%281000%20x%201000%20px%29.png` },
 { id: 483, name: 'Pasted File V4Pgra I Run On Coffee And Chaos', price: 38, collection: 'Graphic Tees', image: `/images/pasted_file_v4pGRa_I%20run%20on%20coffee%20and%20chaos.png` },
 { id: 484, name: 'Pasted File Wg52P1 Sentimental Mother’S', price: 39, collection: 'Graphic Tees', image: `/images/pasted_file_wg52P1_Sentimental%20Mother%E2%80%99s.png` },
 { id: 485, name: 'Pasted File Y7Kb0D Hippo Of Half‑Finished Projects', price: 40, collection: 'Graphic Tees', image: `/images/pasted_file_y7KB0d_Hippo%20of%20Half%E2%80%91Finished%20Projects.webp` },
 { id: 486, name: 'Pasted File Yw7Omk Shooting Stars (1000 X 1000 Px)', price: 41, collection: 'Graphic Tees', image: `/images/pasted_file_yW7OmK_Shooting%20Stars%20%281000%20x%201000%20px%29.png` },
 { id: 487, name: 'Pasted File Yyrdam Mom, The Ultimate Search Engine', price: 42, collection: 'Graphic Tees', image: `/images/pasted_file_yYrDAm_Mom%2C%20the%20ultimate%20search%20engine.png` },
 { id: 488, name: 'Pasted File Ykel71 First My Mother, Forever My Friend 2', price: 43, collection: 'Graphic Tees', image: `/images/pasted_file_ykeL71_First%20my%20mother%2C%20forever%20my%20friend%202.png` },
 { id: 489, name: 'Pasted File Yrgsx5 Cozy Vibes', price: 44, collection: 'Graphic Tees', image: `/images/pasted_file_yrGSX5_COZY%20VIBES.webp` },
 { id: 490, name: 'Pasted File Yz6Oxe Leaving In 5 Minutes… Not Really', price: 45, collection: 'Graphic Tees', image: `/images/pasted_file_yz6OXe_Leaving%20in%205%20Minutes%E2%80%A6%20Not%20Really.png` },
 { id: 491, name: 'Pasted File Zgnp1D Leaving In 5 Minutes… Not Really', price: 46, collection: 'Graphic Tees', image: `/images/pasted_file_zGnP1d_Leaving%20in%205%20Minutes%E2%80%A6%20Not%20Really.webp` },
 { id: 492, name: 'Pasted File Zpxdhj Strong, Kind, Fierce Mom Power', price: 47, collection: 'Graphic Tees', image: `/images/pasted_file_zpXDHj_Strong%2C%20kind%2C%20fierce%20mom%20power.png` },
 { id: 493, name: 'Pink Fight ', price: 48, collection: 'Graphic Tees', image: `/images/pink%20fight%20.png` },
 { id: 494, name: 'Running On Chaos And Moonlight', price: 49, collection: 'Graphic Tees', image: `/images/running%20on%20chaos%20and%20moonlight.png` },
 { id: 495, name: 'Scare Away Breast Cancer', price: 50, collection: 'Graphic Tees', image: `/images/scare%20away%20breast%20cancer.png` },
 { id: 496, name: 'Soft Life', price: 51, collection: 'Graphic Tees', image: `/images/soft%20life.png` },
 { id: 497, name: 'Stfu I Got Kids', price: 52, collection: 'Graphic Tees', image: `/images/stfu_i_got_kids.png` },
 { id: 498, name: 'Support, Admire, Honor', price: 53, collection: 'Graphic Tees', image: `/images/support%2C%20admire%2C%20honor.png` },
 { id: 499, name: 'Tackle Cancer Football', price: 54, collection: 'Graphic Tees', image: `/images/tackle%20cancer%20football.png` },
 { id: 500, name: 'Temp 17W2Fgprmhnp9F4Arkvpyk Na1Fn Twltasdzy29Sb3Jmdwxjcmvhdgl2Zxnhbmn0Dwfyes5Wbmdquk9Gsuxfueld', price: 55, collection: 'Graphic Tees', image: `/images/temp-17w2fGpRmHNP9F4arkvPYk_na1fn_TWltaSdzY29sb3JmdWxjcmVhdGl2ZXNhbmN0dWFyeS5wbmdQUk9GSUxFUElD.png` },
 { id: 501, name: 'Temp 6Rvcmugqwgbxvjn3How93W Na1Fn S29Hbgenc292Zxj3Agvsbwluz3N1Cnzpdmfscgxhbg', price: 56, collection: 'Graphic Tees', image: `/images/temp-6rVCmUgqWgbxVjN3HoW93W_na1fn_S29hbGEnc292ZXJ3aGVsbWluZ3N1cnZpdmFscGxhbg.png` },
 { id: 502, name: 'Temp Cldt7Fah5Vbp9Bkxaaqrnf Na1Fn Tulnssdtq09Awunpuk5Fukjbtk5Fuihjbnn0Ywdyyw1Qb3N0Kdq1Ksk', price: 57, collection: 'Graphic Tees', image: `/images/temp-ClDT7fah5vBp9BKXAaqrnF_na1fn_TUlNSSdTQ09aWUNPUk5FUkJBTk5FUihJbnN0YWdyYW1Qb3N0KDQ1KSk.png` },
 { id: 503, name: 'Temp D17Luhxgyv739Xh62Hlpdc Na1Fn Ssdnbm90Ewvsbgluzyxjj21Qyxjlbnrpbmc', price: 58, collection: 'Graphic Tees', image: `/images/temp-D17LUHxgyv739XH62HLpdC_na1fn_SSdNbm90eWVsbGluZyxJJ21QYXJlbnRpbmc.png` },
 { id: 504, name: 'Temp Dabrh3Zxao0Dswa8Pqqj6X Na1Fn Rg9Nj3Nzdxj2Axzhbg1Vcm5Pbmdodxn0Bgu', price: 59, collection: 'Graphic Tees', image: `/images/temp-DaBrH3ZXaO0DswA8pQqj6X_na1fn_RG9nJ3NzdXJ2aXZhbG1vcm5pbmdodXN0bGU.png` },
 { id: 505, name: 'Temp Ngjsvjizxftx5Lcwx28Zk9 Na1Fn Qw1Vbsdzy2Hhb3Rpy3N1Cgvyagvyb21Vbwvuda', price: 18, collection: 'Graphic Tees', image: `/images/temp-NGjSvjizxFtX5LCwx28zK9_na1fn_QW1vbSdzY2hhb3RpY3N1cGVyaGVyb21vbWVudA.png` },
 { id: 506, name: 'Temp Oghx7Pmuwskkznh49Ovbqq Na1Fn V29Ybgqnc2Dyzwf0Zxn0Bw9Tyxdhcmq', price: 19, collection: 'Graphic Tees', image: `/images/temp-OGhX7PMUwSkkZnH49oVBqQ_na1fn_V29ybGQnc2dyZWF0ZXN0bW9tYXdhcmQ.png` },
 { id: 507, name: 'Temp Psh4A2M2Tkd6Ynkrqm1Lrr Na1Fn Cgfzdgvkx2Zpbgvfz3Pkblzhx01Jtuknu0Npwlldt1Jorvjcqu5Orviosw5Zdgfncmftug9Zdcg0Nskp', price: 20, collection: 'Graphic Tees', image: `/images/temp-PSH4a2m2tKD6ynKRQm1LrR_na1fn_cGFzdGVkX2ZpbGVfZ3pKblZhX01JTUknU0NPWllDT1JORVJCQU5ORVIoSW5zdGFncmFtUG9zdCg0NSkp.png` },
 { id: 508, name: 'Temp Rlmeryl3Lw6Urpmndzyco8 Na1Fn Tw9Tj3Nqyxnzaxzlugfyzw50Aw5Ntw9Tzw50', price: 21, collection: 'Graphic Tees', image: `/images/temp-RlMeryl3lw6uRPMndzYCO8_na1fn_TW9tJ3NQYXNzaXZlUGFyZW50aW5nTW9tZW50.png` },
 { id: 509, name: 'Temp Skfnnkf3Lra54Cf4Fasiqd Na1Fn Cgfzdgvkx2Zpbgvfb2Kxr2Pux0Kntw5Vdhllbgxpbmcsssdtugfyzw50Aw5N', price: 22, collection: 'Graphic Tees', image: `/images/temp-SKfnNKF3Lra54CF4FasiQD_na1fn_cGFzdGVkX2ZpbGVfb2kxR2puX0knTW5vdHllbGxpbmcsSSdtUGFyZW50aW5n.png` },
 { id: 510, name: 'Temp Sjjv8Am4Daqx6Hdfqaq4Mi Na1Fn Twltasdzq296Eunvcm5Lckxvz28', price: 23, collection: 'Graphic Tees', image: `/images/temp-SjJv8am4DaqX6hdfqAQ4MI_na1fn_TWltaSdzQ296eUNvcm5lckxvZ28.jpg` },
 { id: 511, name: 'Temp Vvbtpmmmmpdm3Dup5Rfd7Y Na1Fn Cgfzdgvkx2Zpbgvfnvk1Zjlyx0Tvywxhj3Nvdmvyd2Hlbg1Pbmdzdxj2Axzhbhbsyw4', price: 24, collection: 'Graphic Tees', image: `/images/temp-VVbTpMMMmpdm3DUP5rFd7Y_na1fn_cGFzdGVkX2ZpbGVfNVk1ZjlyX0tvYWxhJ3NvdmVyd2hlbG1pbmdzdXJ2aXZhbHBsYW4.png` },
 { id: 512, name: 'Temp Ykqz5Gxlek5Ul2Ayhpizle Na1Fn Cgfzdgvkx2Zpbgvfwxhxrzzsx01Vbsdzcgfzc2L2Zxbhcmvudgluz21Vbwvuda', price: 25, collection: 'Graphic Tees', image: `/images/temp-YKqZ5GXLek5UL2ayHPiZle_na1fn_cGFzdGVkX2ZpbGVfWXhXRzZSX01vbSdzcGFzc2l2ZXBhcmVudGluZ21vbWVudA.webp` },
 { id: 513, name: 'Temp Yagcsum1Frz5Eu7Unwwbj5 Na1Fn V09Ss0Vsluzfqvjnrsxnt1Juquxtlekntvnmsudivexzr1Jvtvbziq', price: 26, collection: 'Graphic Tees', image: `/images/temp-YagCsUM1FRz5Eu7uNWWBj5_na1fn_V09SS0VSLUZFQVJNRSxNT1JUQUxTLEknTVNMSUdIVExZR1JVTVBZIQ.png` },
 { id: 514, name: 'Temp Z867Aldes1Ldapv4Wrflzf Na1Fn Qu1Vdghlcidztg92Zuhhc05Vtgltaxqomzawmhgyndawkxm', price: 27, collection: 'Graphic Tees', image: `/images/temp-Z867aLDes1lDapV4wrFlzf_na1fn_QU1vdGhlcidzTG92ZUhhc05vTGltaXQoMzAwMHgyNDAwKXM.webp` },
 { id: 515, name: 'Temp Ajfki2Pco0Qohb6Ej2Ylp0 Na1Fn U3Bvbmdlqm9Ij3N0Zwe', price: 28, collection: 'Graphic Tees', image: `/images/temp-ajfkI2pco0QohB6Ej2YLP0_na1fn_U3BvbmdlQm9iJ3N0ZWE.png` },
 { id: 516, name: 'Temp Bilx69R8Iyvwbv0Wrzntxe Na1Fn Qu1Vdghlcidztg92Zuhhc05Vtgltaxrzmzj4Mzi', price: 29, collection: 'Graphic Tees', image: `/images/temp-bILX69r8IyVWbV0wRZNtxE_na1fn_QU1vdGhlcidzTG92ZUhhc05vTGltaXRzMzJ4MzI.webp` },
 { id: 517, name: 'Temp J323Xjqprczb2Rpw8Rz91M Na1Fn Tulnssdtq09Awunpuk5Fukjbtk5Fug', price: 30, collection: 'Graphic Tees', image: `/images/temp-j323xJQpRCZB2rPW8RZ91M_na1fn_TUlNSSdTQ09aWUNPUk5FUkJBTk5FUg.png` },
 { id: 518, name: 'Temp Lpvqtdqm40Tmdxvgsymtzx Na1Fn Cgfzdgvkx2Zpbgvfctvdrmx6X01Hbwenc2Zvcmv2Zxjsb3Zlyw5Kywzmzwn0Aw9U', price: 31, collection: 'Graphic Tees', image: `/images/temp-lpvqtdQM40TMdxvGsYmTZX_na1fn_cGFzdGVkX2ZpbGVfcTVDRmx6X01hbWEnc2ZvcmV2ZXJsb3ZlYW5kYWZmZWN0aW9u.png` },
 { id: 519, name: 'Temp Mykmntk1Eyq3Lispskpzni Na1Fn Twltasdzy296Ewnyywz0Aw5Nc3Bhy2U', price: 32, collection: 'Graphic Tees', image: `/images/temp-mykMNTk1eyQ3LiSpSKpZnI_na1fn_TWltaSdzY296eWNyYWZ0aW5nc3BhY2U.png` },
 { id: 520, name: 'Temp Pcesv05Lxttmbfhfehp2H9 Na1Fn Qu1Vdghlcidztg92Zuhhc05Vtgltaxrzmja0Ohgymdq4', price: 33, collection: 'Graphic Tees', image: `/images/temp-pCEsV05lxTTMBFhFEHP2h9_na1fn_QU1vdGhlcidzTG92ZUhhc05vTGltaXRzMjA0OHgyMDQ4.png` },
 { id: 521, name: 'Temp Ppoqtkmc1S3Lycbj5Ynwvl Na1Fn Twftysdzzm9Yzxzlcmxvdmvhbmrhzmzly3Rpb24 (1)', price: 34, collection: 'Graphic Tees', image: `/images/temp-pPOqTKmC1s3LYcBj5ynWVl_na1fn_TWFtYSdzZm9yZXZlcmxvdmVhbmRhZmZlY3Rpb24%20%281%29.png` },
 { id: 522, name: 'Temp Ppoqtkmc1S3Lycbj5Ynwvl Na1Fn Twftysdzzm9Yzxzlcmxvdmvhbmrhzmzly3Rpb24', price: 35, collection: 'Graphic Tees', image: `/images/temp-pPOqTKmC1s3LYcBj5ynWVl_na1fn_TWFtYSdzZm9yZXZlcmxvdmVhbmRhZmZlY3Rpb24.png` },
 { id: 523, name: 'Temp Tirnphvcslyur3Ukh1Rhfz Na1Fn Qw1Vdghlcidzbg92Zwhhc25Vbgltaxrz', price: 36, collection: 'Graphic Tees', image: `/images/temp-tIrNPHVcSLyuR3UKH1RHfZ_na1fn_QW1vdGhlcidzbG92ZWhhc25vbGltaXRz.png` },
 { id: 524, name: 'Temp Xrkfy6Cjdrjv4Gistf4Sxy Na1Fn Qxnvbidzzmlyc3Rozxjvlgfkyxvnahrlcidzzmlyc3Rmcmllbmq', price: 37, collection: 'Graphic Tees', image: `/images/temp-xRKFy6cJdRJV4gistf4Sxy_na1fn_QXNvbidzZmlyc3RoZXJvLGFkYXVnaHRlcidzZmlyc3RmcmllbmQ.png` },
 { id: 525, name: 'Temp Ynkmzlpkcfwagqtcghvtfl Na1Fn Cgfzdgvkx2Zpbgvfc01Ya0W3X01Hbwenc2Zvcmv2Zxjsb3Zlyw5Kywzmzwn0Aw9U', price: 38, collection: 'Graphic Tees', image: `/images/temp-yNKMzlPkcfWAgqTCGhVtFl_na1fn_cGFzdGVkX2ZpbGVfc01ya0w3X01hbWEnc2ZvcmV2ZXJsb3ZlYW5kYWZmZWN0aW9u.png` },
 { id: 526, name: 'Valentine Ghost Be My Boo', price: 39, collection: 'Graphic Tees', image: `/images/valentine-ghost%20be%20my%20boo.png` },
 { id: 527, name: 'Warrior', price: 40, collection: 'Graphic Tees', image: `/images/warrior.png` },
 { id: 528, name: '“My Dad’S Superpower Is Losing His Keys.”', price: 41, collection: 'Graphic Tees', image: `/images/%E2%80%9CMy%20Dad%E2%80%99s%20Superpower%20Is%20Losing%20His%20Keys.%E2%80%9D.png` },
 { id: 529, name: '“You Never Left — I Just Stopped Listening. I Hear You Now.”', price: 42, collection: 'Graphic Tees', image: `/images/%E2%80%9CYou%20never%20left%20%E2%80%94%20I%20just%20stopped%20listening.%20I%20hear%20you%20now.%E2%80%9D.png` },
 { id: 530, name: '“You’Re Allowed To Be Here.”I’M Not Afraid Of You.” You Can Take Your Time.”( Using A Triple Image Using Dull Colors)', price: 43, collection: 'Graphic Tees', image: `/images/%E2%80%9CYou%E2%80%99re%20allowed%20to%20be%20here.%E2%80%9DI%E2%80%99m%20not%20afraid%20of%20you.%E2%80%9D%20You%20can%20take%20your%20time.%E2%80%9D%28%20using%20a%20triple%20image%20using%20dull%20colors%29.png` },
]
export default function App(){
  const [active, setActive] = useState("All")
  const [cart, setCart] = useState<Product[]>([])
  const [search, setSearch] = useState("")
  const filtered = useMemo(()=>{ return PRODUCTS.filter(p=>{ const matchCol = active==="All" || p.collection===active; const matchSearch = p.name.toLowerCase().includes(search.toLowerCase()); return matchCol && matchSearch }) },[active, search])
  return (<div style={{fontFamily:'Inter, system-ui, sans-serif', background:'#fff', color:'#111', minHeight:'100vh'}}><header style={{background:'#fff', borderBottom:'1px solid #eee', position:'sticky', top:0, zIndex:50}}><div style={{maxWidth:'1300px', margin:'0 auto', padding:'18px 20px', display:'flex', justifyContent:'space-between', alignItems:'center'}}><div><h1 style={{margin:0, fontSize:'22px', letterSpacing:'4px', fontWeight:900}}>MIMI'S COZY CORNER</h1><div style={{fontSize:'10px', letterSpacing:'4px', marginTop:'4px', color:'#666'}}>EST. 2023 • {PRODUCTS.length} PRODUCTS LIVE</div></div><div style={{display:'flex', gap:'12px', alignItems:'center'}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${PRODUCTS.length}...`} style={{border:'1px solid #000', padding:'8px 12px', width:'180px'}} /><div style={{border:'1px solid #000', padding:'8px 16px', fontWeight:700}}>CART ({cart.length})</div></div></div><div style={{borderTop:'1px solid #f2f2f2', overflowX:'auto', whiteSpace:'nowrap', padding:'10px 20px', display:'flex', gap:'8px', justifyContent:'center'}}>{COLLECTIONS.map(c=>(<button key={c} onClick={()=>setActive(c)} style={{padding:'6px 14px', border:'1px solid #000', background: active===c? '#000' : '#fff', color: active===c? '#fff' : '#000', fontSize:'11px', fontWeight:700, letterSpacing:'1px', cursor:'pointer', textTransform:'uppercase'}}>{c}</button>))}</div></header><section style={{background:'#fff', textAlign:'center', padding:'50px 20px 30px'}}><h2 style={{fontSize:'38px', margin:'0 0 10px', letterSpacing:'-1px'}}>COZY COLLECTION LIVE</h2><p style={{color:'#666', margin:0}}>{filtered.length} Real Products • Free Shipping Over $75</p></section><main style={{maxWidth:'1300px', margin:'0 auto', padding:'0 20px 80px'}}><div style={{display:'grid', gridTemplateColumns:'repeat(auto-fill, minmax(220px,1fr))', gap:'20px'}}>{filtered.map(p=>(<div key={p.id} style={{border:'1px solid #eee', background:'#fff'}}><div style={{aspectRatio:'1', background:'#f9f9f9', overflow:'hidden'}}><img src={p.image} alt={p.name} style={{width:'100%', height:'100%', objectFit:'cover'}} loading="lazy" /></div><div style={{padding:'12px'}}><div style={{fontSize:'10px', letterSpacing:'2px', color:'#999', textTransform:'uppercase'}}>{p.collection}</div><div style={{fontSize:'14px', fontWeight:600, margin:'4px 0'}}>{p.name}</div><div style={{display:'flex', justifyContent:'space-between', alignItems:'center', marginTop:'8px'}}><span style={{fontWeight:900}}>${p.price}.00</span><button onClick={()=>setCart([...cart, p])} style={{background:'#000', color:'#fff', border:'none', padding:'6px 12px', fontSize:'11px', fontWeight:700, cursor:'pointer'}}>ADD</button></div></div></div>))}</div></main><footer style={{background:'#000', color:'#fff', textAlign:'center', padding:'30px', fontSize:'11px', letterSpacing:'3px'}}>MIMI'S COZY CORNER • 530 PRODUCTS LIVE</footer></div>)
}
