import React, { useState, useMemo } from "react"
type Product = { id:number; name:string; price:number; collection:string; image:string }
const COLLECTIONS = ["All","Western","Trucker Hats","Bags","Fall","Graphic Tees","Hoodies","Shirts","Sweatshirts","Outerwear","Jewelry","Footwear","Bottoms","Accessories","Sale","New"]
const PRODUCTS: Product[] = [
 { id: 1, name: 'Best Dad By Par', price: 18, collection: 'Graphic Tees', image: `/images/Best%20Dad%20By%20Par.png` },
 { id: 2, name: 'Dad Because Grandpa Wasn’T Cool Enough', price: 19, collection: 'Graphic Tees', image: `/images/Dad%20Because%20Grandpa%20Wasn%E2%80%99t%20Cool%20Enough.png` },
 { id: 3, name: 'Dad Bod Built By Bbq And Bad Decisions', price: 20, collection: 'Graphic Tees', image: `/images/Dad%20Bod%20Built%20by%20BBQ%20and%20Bad%20Decisions.png` },
 { id: 4, name: 'Dad Fueling The Family With Dad Jokes & Coffee', price: 21, collection: 'Graphic Tees', image: `/images/Dad%20Fueling%20the%20Family%20With%20Dad%20Jokes%20%26%20Coffee.png` },
 { id: 5, name: 'Dad Jokes Are How Eye Roll', price: 22, collection: 'Graphic Tees', image: `/images/Dad%20Jokes%20Are%20How%20Eye%20Roll.png` },
 { id: 6, name: 'Dad Life Powered By Coffee And Patience', price: 23, collection: 'Graphic Tees', image: `/images/Dad%20Life%20Powered%20by%20Coffee%20and%20Patience.png` },
 { id: 7, name: 'Dad Master Of The Remote Control', price: 24, collection: 'Graphic Tees', image: `/images/Dad%20Master%20of%20the%20Remote%20Control.png` },
 { id: 8, name: 'Dad Professional Thermostat Protector', price: 25, collection: 'Graphic Tees', image: `/images/Dad%20Professional%20Thermostat%20Protector.png` },
 { id: 9, name: 'Dad Sacrificing Sleep Since Forever', price: 26, collection: 'Graphic Tees', image: `/images/Dad%20Sacrificing%20Sleep%20Since%20Forever.png` },
 { id: 10, name: 'Dad Tax Taking A Piece Of Your Snacks Since Day One', price: 27, collection: 'Graphic Tees', image: `/images/Dad%20Tax%20Taking%20a%20Piece%20of%20Your%20Snacks%20Since%20Day%20One.png` },
 { id: 11, name: 'Dad The Human Instructions Nobody Reads', price: 28, collection: 'Graphic Tees', image: `/images/Dad%20The%20Human%20Instructions%20Nobody%20Reads.png` },
 { id: 12, name: 'Dad’S Bbq Rule #1 If I’M Cooking, Stay Out Of My Kitchen', price: 29, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20BBQ%20Rule%20%231%20If%20I%E2%80%99m%20Cooking%2C%20Stay%20Out%20of%20My%20Kitchen.png` },
 { id: 13, name: 'Dad’S Chair Touch It And You’Re Grounded', price: 30, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Chair%20Touch%20It%20and%20You%E2%80%99re%20Grounded.png` },
 { id: 14, name: 'Dad’S Cooking Timer “I’Ll Know When It’S Done”', price: 31, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Cooking%20Timer%20%E2%80%9CI%E2%80%99ll%20Know%20When%20It%E2%80%99s%20Done%E2%80%9D.png` },
 { id: 15, name: 'Dad’S Driving Rules Silence Means I Missed The Turn', price: 32, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Driving%20Rules%20Silence%20Means%20I%20Missed%20the%20Turn.png` },
 { id: 16, name: 'Dad’S Favorite Child Depends On Who Has Snacks', price: 33, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Favorite%20Child%20Depends%20on%20Who%20Has%20Snacks.png` },
 { id: 17, name: 'Dad’S Favorite Exercise Walking To The Fridge', price: 34, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Favorite%20Exercise%20Walking%20to%20the%20Fridge.png` },
 { id: 18, name: 'Dad’S Garage My Tools, My Rules', price: 35, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Garage%20My%20Tools%2C%20My%20Rules.png` },
 { id: 19, name: 'Dad’S Garage Where Projects Go To Never Be Finished', price: 36, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Garage%20Where%20Projects%20Go%20to%20Never%20Be%20Finished.png` },
 { id: 20, name: 'Dad’S Gas Station Stop Somehow Costs $47 Every Time', price: 37, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Gas%20Station%20Stop%20Somehow%20Costs%20%2447%20Every%20Time.png` },
 { id: 21, name: 'Dad’S Grill Schedule Burnt Outside, Raw Inside, Full Confidence', price: 38, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Grill%20Schedule%20Burnt%20Outside%2C%20Raw%20Inside%2C%20Full%20Confidence.png` },
 { id: 22, name: 'Dad’S Grocery Store Mission Go In For One Thing, Leave With 37 Snacks', price: 39, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Grocery%20Store%20Mission%20Go%20In%20for%20One%20Thing%2C%20Leave%20With%2037%20Snacks.png` },
 { id: 23, name: 'Dad’S Hearing Works Selectively', price: 40, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Hearing%20Works%20Selectively.png` },
 { id: 24, name: 'Dad’S Lawn Rules Stripes Matter More Than Feelings', price: 41, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Lawn%20Rules%20Stripes%20Matter%20More%20Than%20Feelings.png` },
 { id: 25, name: 'Dad’S Nap The Most Protected Event In The House', price: 42, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Nap%20The%20Most%20Protected%20Event%20in%20the%20House.png` },
 { id: 26, name: 'Dad’S Official Language Grunts, Sighs & Dad Jokes', price: 43, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Official%20Language%20Grunts%2C%20Sighs%20%26%20Dad%20Jokes.png` },
 { id: 27, name: 'Dad’S Remote Control Rights Nobody Else Touches It', price: 44, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Remote%20Control%20Rights%20Nobody%20Else%20Touches%20It.png` },
 { id: 28, name: 'Dad’S Snack Stash Hidden Better Than Government Secrets', price: 45, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Snack%20Stash%20Hidden%20Better%20Than%20Government%20Secrets.png` },
 { id: 29, name: 'Dad’S Texting Style One Word Replies & Zero Punctuation', price: 46, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Texting%20Style%20One%20Word%20Replies%20%26%20Zero%20Punctuation.png` },
 { id: 30, name: 'Dad’S Toolbox Full Of Tools He’Ll Never Let You Borrow', price: 47, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Toolbox%20Full%20of%20Tools%20He%E2%80%99ll%20Never%20Let%20You%20Borrow.png` },
 { id: 31, name: 'Dad’S Universal Fix “Put Some Duct Tape On It”', price: 48, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Universal%20Fix%20%E2%80%9CPut%20Some%20Duct%20Tape%20On%20It%E2%80%9D.png` },
 { id: 32, name: 'Dad’S Vacation Packing List 14 Cords, 2 Coolers & Zero Shirts', price: 49, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Vacation%20Packing%20List%2014%20Cords%2C%202%20Coolers%20%26%20Zero%20Shirts.png` },
 { id: 33, name: 'Dad’S Wallet Opens Faster At The Hardware Store', price: 50, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Wallet%20Opens%20Faster%20at%20the%20Hardware%20Store.png` },
 { id: 34, name: 'Dad’S Weather Forecast “Yep… It’S Hot Outside”', price: 51, collection: 'Graphic Tees', image: `/images/Dad%E2%80%99s%20Weather%20Forecast%20%E2%80%9CYep%E2%80%A6%20It%E2%80%99s%20Hot%20Outside%E2%80%9D.png` },
 { id: 35, name: 'Happy Father’S Day To The Guy Who Always Knows A Shortcut', price: 52, collection: 'Graphic Tees', image: `/images/Happy%20Father%E2%80%99s%20Day%20to%20the%20Guy%20Who%20Always%20Knows%20a%20Shortcut.png` },
 { id: 36, name: 'Happy Father’S Day To The Guy Who Still Thinks He’S Funny', price: 53, collection: 'Graphic Tees', image: `/images/Happy%20Father%E2%80%99s%20Day%20to%20the%20Guy%20Who%20Still%20Thinks%20He%E2%80%99s%20Funny.png` },
 { id: 37, name: 'Happy Father’S Day To The King Of Dad Jokes', price: 54, collection: 'Graphic Tees', image: `/images/Happy%20Father%E2%80%99s%20Day%20to%20the%20King%20of%20Dad%20Jokes.png` },
 { id: 38, name: 'Happy Father’S Day To The Original Superhero', price: 55, collection: 'Graphic Tees', image: `/images/Happy%20Father%E2%80%99s%20Day%20to%20the%20Original%20Superhero.png` },
 { id: 39, name: 'I Can’T Fix Stupid, But I Can Fix Most Things', price: 56, collection: 'Graphic Tees', image: `/images/I%20Can%E2%80%99t%20Fix%20Stupid%2C%20But%20I%20Can%20Fix%20Most%20Things.png` },
 { id: 40, name: 'I Don’T Snore. I Dream I’M A Motorcycle.', price: 57, collection: 'Graphic Tees', image: `/images/I%20Don%E2%80%99t%20Snore.%20I%20Dream%20I%E2%80%99m%20a%20Motorcycle..png` },
 { id: 41, name: 'I Make Awesome Kids. You’Re Welcome.', price: 58, collection: 'Graphic Tees', image: `/images/I%20Make%20Awesome%20Kids.%20You%E2%80%99re%20Welcome..png` },
 { id: 42, name: 'I’M Not Arguing. I’M Just Explaining Why I’M Right.', price: 59, collection: 'Graphic Tees', image: `/images/I%E2%80%99m%20Not%20Arguing.%20I%E2%80%99m%20Just%20Explaining%20Why%20I%E2%80%99m%20Right..png` },
 { id: 43, name: 'Thanks For Teaching Me Everything… Except How To Be Quiet', price: 18, collection: 'Graphic Tees', image: `/images/Thanks%20for%20Teaching%20Me%20Everything%E2%80%A6%20Except%20How%20to%20Be%20Quiet.png` },
 { id: 44, name: 'World’S Okayest Dad (But Still A Legend)', price: 19, collection: 'Graphic Tees', image: `/images/World%E2%80%99s%20Okayest%20Dad%20%28But%20Still%20a%20Legend%29.png` },
 { id: 45, name: 'You’Re Grill Ious, Dad!', price: 20, collection: 'Graphic Tees', image: `/images/You%E2%80%99re%20Grill-ious%2C%20Dad%21.png` },
 { id: 46, name: 'You’Re The Coolest Dad This Side Of The Grill', price: 21, collection: 'Graphic Tees', image: `/images/You%E2%80%99re%20the%20Coolest%20Dad%20This%20Side%20of%20the%20Grill.png` },
 { id: 47, name: 'Mimis Cozy Corner White Logo', price: 22, collection: 'Graphic Tees', image: `/images/mimis_cozy_corner_White%20logo.webp` },
 { id: 48, name: 'Mimis Cozy Corner Ad Asset Youtube', price: 23, collection: 'Graphic Tees', image: `/images/mimis_cozy_corner_ad_asset-YouTube.png` },
 { id: 49, name: 'Mimis Cozy Corner Magenta', price: 24, collection: 'Graphic Tees', image: `/images/mimis_cozy_corner_magenta.webp` },
]
export default function App(){
  const [active, setActive] = useState("All")
  const [cart, setCart] = useState<Product[]>([])
  const [search, setSearch] = useState("")
  const filtered = useMemo(()=>{ return PRODUCTS.filter(p=>{ const matchCol = active==="All" || p.collection===active; const matchSearch = p.name.toLowerCase().includes(search.toLowerCase()); return matchCol && matchSearch }) },[active, search])
  return (<div style={{fontFamily:'Inter, system-ui, sans-serif', background:'#fff', color:'#111', minHeight:'100vh'}}><header style={{background:'#fff', borderBottom:'1px solid #eee', position:'sticky', top:0, zIndex:50}}><div style={{maxWidth:'1300px', margin:'0 auto', padding:'18px 20px', display:'flex', justifyContent:'space-between', alignItems:'center'}}><div><h1 style={{margin:0, fontSize:'22px', letterSpacing:'4px', fontWeight:900}}>MIMI'S COZY CORNER</h1><div style={{fontSize:'10px', letterSpacing:'4px', marginTop:'4px', color:'#666'}}>EST. 2023 • {PRODUCTS.length} PRODUCTS LIVE</div></div><div style={{display:'flex', gap:'12px', alignItems:'center'}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${PRODUCTS.length}...`} style={{border:'1px solid #000', padding:'8px 12px', width:'180px'}} /><div style={{border:'1px solid #000', padding:'8px 16px', fontWeight:700}}>CART ({cart.length})</div></div></div><div style={{borderTop:'1px solid #f2f2f2', overflowX:'auto', whiteSpace:'nowrap', padding:'10px 20px', display:'flex', gap:'8px', justifyContent:'center'}}>{COLLECTIONS.map(c=>(<button key={c} onClick={()=>setActive(c)} style={{padding:'6px 14px', border:'1px solid #000', background: active===c? '#000' : '#fff', color: active===c? '#fff' : '#000', fontSize:'11px', fontWeight:700, letterSpacing:'1px', cursor:'pointer', textTransform:'uppercase'}}>{c}</button>))}</div></header><section style={{background:'#fff', textAlign:'center', padding:'50px 20px 30px'}}><h2 style={{fontSize:'38px', margin:'0 0 10px', letterSpacing:'-1px'}}>COZY COLLECTION LIVE</h2><p style={{color:'#666', margin:0}}>{filtered.length} Real Products • Free Shipping Over $75</p></section><main style={{maxWidth:'1300px', margin:'0 auto', padding:'0 20px 80px'}}><div style={{display:'grid', gridTemplateColumns:'repeat(auto-fill, minmax(220px,1fr))', gap:'20px'}}>{filtered.map(p=>(<div key={p.id} style={{border:'1px solid #eee', background:'#fff'}}><div style={{aspectRatio:'1', background:'#f9f9f9', overflow:'hidden'}}><img src={p.image} alt={p.name} style={{width:'100%', height:'100%', objectFit:'cover'}} loading="lazy" /></div><div style={{padding:'12px'}}><div style={{fontSize:'10px', letterSpacing:'2px', color:'#999', textTransform:'uppercase'}}>{p.collection}</div><div style={{fontSize:'14px', fontWeight:600, margin:'4px 0'}}>{p.name}</div><div style={{display:'flex', justifyContent:'space-between', alignItems:'center', marginTop:'8px'}}><span style={{fontWeight:900}}>${p.price}.00</span><button onClick={()=>setCart([...cart, p])} style={{background:'#000', color:'#fff', border:'none', padding:'6px 12px', fontSize:'11px', fontWeight:700, cursor:'pointer'}}>ADD</button></div></div></div>))}</div></main><footer style={{background:'#000', color:'#fff', textAlign:'center', padding:'30px', fontSize:'11px', letterSpacing:'3px'}}>MIMI'S COZY CORNER • 49 PRODUCTS LIVE</footer></div>)
}
